### PR TITLE
defined reified classes with their parent class's classloader as parent

### LINKED ISSUE #7327: Can't extend a Java class in JRuby when the parent class is not in the system class loader
I'm starting my JVM process as JRuby `bundle console`, and then loading a bunch of Java stuff that uses non-system class loaders (technically it's Apache Karaf with Eclipse Equinox OSGi implementation). I then define a new Ruby class that inherits from a Java class in a Bundle that's not on the system class loader. I've added a loader with `JRuby.runtime.instance_config.add_loader` (essentially `org.jruby.embed.osgi.OSGiIsolatedScriptingContainer$BundleGetResources`, but I had to re-implement in Ruby since the former can't be used because org.osgi.framework.Bundle itself can't be found by the system class loader). This allows me to access the classes in the bundle from Ruby. But when I try to inherit from one, and it gets reified, I get `org/jruby/java/addons/ClassJavaAddons.java:65:in 'become_java!': requested class OpenHAB::DSL::Rules::AutomationRule was not reifiable (TypeError)`. Enabling `jruby.reify.logErrors=true`, I get additional logging:

```
2022-08-24T16:02:45.213-06:00 [main] ERROR RubyClass : failed to reify class OpenHAB::DSL::Rules::AutomationRule due to: 
java.lang.NoClassDefFoundError: org/openhab/core/automation/module/script/rulesupport/shared/simple/SimpleRule
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.jruby.dist/org.jruby.util.ClassDefiningJRubyClassLoader.defineClass(ClassDefiningJRubyClassLoader.java:53)
	at org.jruby.dist/org.jruby.RubyClass.reify(RubyClass.java:1368)
	at org.jruby.dist/org.jruby.RubyClass.reifyWithAncestors(RubyClass.java:1305)
	at org.jruby.dist/org.jruby.java.addons.ClassJavaAddons.becomeJava(ClassJavaAddons.java:91)
	at org.jruby.dist/org.jruby.java.addons.ClassJavaAddons.become_java(ClassJavaAddons.java:85)
	at org.jruby.dist/org.jruby.java.addons.ClassJavaAddons$INVOKER$s$become_java.call(ClassJavaAddons$INVOKER$s$become_java.gen)
	at org.jruby.dist/org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:824)
	at org.jruby.dist/org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	at org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372)
	at org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175)
...
Caused by: java.lang.ClassNotFoundException: org.openhab.core.automation.module.script.rulesupport.shared.simple.SimpleRule
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 233 more
```

(I wish I could see the 233 more, but I don't think it's critical to understand the problem. Digging into the JRuby code, there are a couple possibilities for the problem in `RubyClass.reify` (relevant code pasted for reference):
```java
        final byte[] classBytes = reifier.reify();

        final ClassDefiningClassLoader parentCL;
        if (parentReified.getClassLoader() instanceof OneShotClassLoader) {
            parentCL = (OneShotClassLoader) parentReified.getClassLoader();
        } else {
            if (useChildLoader) {
                parentCL = new OneShotClassLoader(runtime.getJRubyClassLoader());
            } else {
                parentCL = runtime.getJRubyClassLoader();
            }
        }
        boolean nearEnd = false;
        // Attempt to load the name we plan to use; skip reification if it exists already (see #1229).
        try {
            Class result = parentCL.defineClass(javaName, classBytes);
```
 * First, runtime.getJRubyClassLoader (which is returning a plain `org.jruby.util.JRubyClassLoader`) doesn't know to search the additional loaders I configured
 * Second, perhaps `parentCL` should actually be a `MultiClassLoader`, as used in `RealClassGenerator.defineRealImplClass`, which adds the superclass's loader as the parent of the `MultiClassLoader`, and then adds all of the `getExtraLoaders` individually, _and then_ wraps it in a `ClassDefiningJRubyClassLoader`.

I'm not familiar enough with JRuby internals to know if either or both of those approaches would have additional pitfalls.

**Environment Information**
 * `jruby 9.3.7.0 (2.6.8) 2022-08-16 c79ef237e0 OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu122.04 on 11.0.16+8-post-Ubuntu-0ubuntu122.04 [x86_64-linux]`
 * `Linux opennuc 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

(btw, thanks for https://blog.jruby.org/2022/06/jruby-class-extension-9.3 - while it didn't explain exactly my problem, it helped me understand the context more).

### PR DESCRIPTION
**Pull request by ccutrer**
fixes #7327

### CODE REVIEW

**Comment by ccutrer** [comment]
The check failure appears to be a simple timeout in unrelated code. This seems to be working, but would welcome any feedback on the approach. Especially the part where I'm _not_ using the MultiClassLoader if useChildLoader is false.

**Comment by headius** [comment]
Yeah this looks fine. Thanks!

**Comment by ccutrer** [comment]
I'm happy with this now, and ready for review.

**Comment by ccutrer** [comment]
@headius: are you waiting for anything else from me on this PR?

**Comment by headius** [comment]
Nope this looks logical and correct! Thank you!

**Pull request merged**
