### PR TITLE
fix Struct#inspect with recursion

### PR DESCRIPTION
**Pull request by lumeet**
Referring to jruby/jruby#2142 the details regarding differences between MRI and JRuby recursion guards are way beyond my understanding. If the code changes suck, I hope this PR at least explains what the problem is. :)

### CODE REVIEW

**Comment by headius** [comment]
PR looks fine to me. Will try it locally.

**Comment by headius** [comment]
Well the changes look fine, but they don't make the test I reported in #2142 pass:

```
~/projects/jruby $ jruby test/mri/runner.rb test_pp.rb
Run options: 

# Running tests:

[ 7/20] PPTestModule::PPCycleTest#test_withinspect = 0.01 s      
  1) Failure:
PPTestModule::PPCycleTest#test_withinspect [/Users/headius/projects/jruby/test/mri/test_pp.rb:157]:
<"[<inspect:[...]>]\n"> expected but was
<"[<inspect:[<inspect:[...]>]>]\n">.
```

Seems like it's doubling up the "inspect:" part.

**Comment by lumeet** [comment]
@headius Don't know how I missed that one. It also seems to be a completely other story, which extends beyond the beginner level, I think. I've been investigating the issue quite a bit but don't know how to continue. `Array#inspect` should perhaps be more like that in `Struct`, which I tried with little success.

As far as I know the first line should be affected by the latter:
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/Ruby.java#L4094
https://github.com/jruby/jruby/blob/master/lib/ruby/stdlib/pp.rb#L164

This seems not to be the case and maybe it's the root of the problem? In MRI, the behavior is the same as in JRuby now if the latter line is left out.

I think I'm going to leave the last part of the issue to someone with a bit more experience of the subject.

**Comment by kares** [comment]
adapted your commit to fit with master updates: https://github.com/jruby/jruby/commit/33bb8d2dc6bd7856965cc0bc8e9b815407439f76?w=1 ... `Struct#inspect` now behaves as MRI the pp test fails the same but as you already find out its a fix to be made elsewhere (not in `Struct`)

**Pull request closed without merging**
