### PR TITLE
#5699:adding the javax maven dependency to avoid "javax.annotation.Ge…

### PR DESCRIPTION
**Pull request by FuncGuy**
fixed the issue annotation not found compiler error.

### CODE REVIEW

**Comment by headius** [comment]
👍

**Comment by mkristian** [comment]
@FuncGuy dependency should be scope `provided` as we do not need this for runtime only for compile time.
BTW please change core/pom.rb, run build and then core/pom.xml will be generated with the changes from core/pom.rb.

**Comment by headius** [comment]
Since @FuncGuy seems to have gone away I'll merge and fix @mkristian comments on master.

**Comment by headius** [comment]
@FuncGuy Ok I was confused when I merged this...the changes in your PR don't actually do anything with the annotation API.

I did a subsequent commit that removed the dependency and plugin you added, and moved the annotation API dependency (which we already had) to the global space so it's active for all profiles of the build.

If this doesn't work you'll need to explain why these other two changes were needed. Please open a new issue for them that describes why you made them.

**Comment by FuncGuy** [comment]
@headius Ok i will try to reproduce if at all possible i'm ok with your fix!!

**Pull request merged**
