### PR TITLE
Clean up structure of io/console and avoid stty on Windows.

### LINKED ISSUE #3989: JRuby + Cygwin + Jenkins causes message related to stty
### Environment

   jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [Windows 7-amd64]
### Expected Behavior
- Ruby should not print warnings related to tty when running on Windows
### Actual Behavior

When I run JRuby on Jenkins, but invoked from a Cygwin shell, I get the annoying warning message

```
stty: standard input: Inappropriate ioctl for device
```

This does not happen when I run JRuby from a (Cygwin-) command line (interactively), or on Jenkins from a Windows command line.

I remember that there was  a very similar error in jruby 1.7.23, where a stty warning was always shown when executing jruby from a Cygwin shell script, even with an interactive one. This error had been fixed in 1.7.24.

Running the script as a Jenkins job means that there is no console associated to the job. Perhaps the bugfix mentioned, did not pay attention to this possibility.

Thomas Enebo commented to this in the JRuby mailing list in the following way: "The gist of things is when you run via cygwin on Jenkins it is from a daemon and it has no tty associated with it.  When we run stty you get this error.  When you run from a cygwin windows it does have a tty so stty completes without issue."

### PR DESCRIPTION
**Pull request by headius**
Fixes #3989.

* Restructure the different impls of console into their own files.
* Always use stubbed version on Windows.
* Cascade from native to stty to stubbed on other platforms.

cc @kares @enebo @jmiettinen

### CODE REVIEW

**Comment by headius** [comment]
@enebo Any concerns?

**Comment by enebo** [comment]
@headius no.  Are you going to get this upstream too?  Or parts of it at least?

**Comment by headius** [comment]
@enebo Upstream where? This is JRuby-specific; in MRI io/console is a C ext. This change will go into both 9k and 1.7.

**Comment by enebo** [comment]
well I meant MRI and forgot it was a cext.

**Pull request merged**
