### PR TITLE
update [net] libraries

### PR DESCRIPTION
**Pull request by ahorek**
refs https://github.com/jruby/jruby/issues/6523

* get rid of ```Timeout.timeout```
* update to latest versions, there were many improvements since the last update

there're two main issues that prevent gemification

1/ missing OpenSSL APIs, mostly SNI support, see
https://github.com/jruby/jruby-openssl/issues/112 https://github.com/jruby/jruby-openssl/issues/103 https://github.com/jruby/jruby-openssl/issues/202
this should be really implemented, but it's skipped for now.

2/ https://github.com/ruby/digest
is a hard dependency and the gem has no JRuby version

### CODE REVIEW

**Comment by headius** [comment]
Have these changes been merged into Ruby 2.6? We generally try to match their standard library exactly and not go beyond it.

**Comment by ahorek** [comment]
changes like https://github.com/ruby/net-smtp/pull/4 https://github.com/ruby/net-smtp/pull/21 were already merged, but they weren't backported to 2.6.

here's a ruby ticket that tracks the promotion to bundled gems https://bugs.ruby-lang.org/issues/17873

> not go beyond it.

I have to admit there's a compatibility concern here, even if I didn't found any issue that could break puma or something like that. We should probably wait with this until JRuby 9.4, but the good part is we know what works, what's missing, and what needs to be done to make this happen.

> Could you open a few issues on JRuby and those libraries to get the process moving?

there are already open issues
1/ jOpenSSL APIs, https://github.com/jruby/jruby-openssl/issues/112
2/ Digest, https://github.com/ruby/digest/issues/20
3/ SSLSocket#session=, and there's also this change https://github.com/jruby/jruby/commit/12082fd045319a760de45842d4d637899edb8048

and release all gems (I think it won't happen before the Ruby 3.1 release, but maybe Ruby maintainers will be willing to do so sooner)

I'm really looking forward to finally address http://blog.headius.com/2008/02/ruby-threadraise-threadkill-timeoutrb.html after 13 years :)

**Comment by headius** [comment]
Agreed on all points, thanks for the links to the key open issues. We will get 9.2.18 out today, then wrap up 9.3 by end of month, and then start the heavy lifting to bring 9.4 in line with Ruby 3.0 including these troublesome gems.

**Comment by headius** [comment]
There is a mild update of net libraries in https://github.com/jruby/jruby/pull/6802, to align them with Ruby 2.6.8.

**Pull request closed without merging**
