### PR TITLE
Only run deploy against actual pushes to our repo

### PR DESCRIPTION
**Pull request by headius**
It was also running for PRs against the master and maintenance
branches.

### CODE REVIEW

**Comment by headius** [comment]
This can be merged if the build does not have the "deploy" stage while still in PR form.

**Comment by kares** [comment]
wouldn't the artifact deployment push become problematic when doing a release ?

**Comment by headius** [comment]
@kares I believe it would just push to the snapshot repo as normal with a release version. I'm not sure if that would be a problem... @mkristian may know more. It should be possible to filter the deploy stage to only try to deploy when version ends in SNAPSHOT.

**Comment by headius** [comment]
Latest tweak does not have the "deploy" stage on PRs, so I'm merging it.

**Comment by mkristian** [comment]
@headius @kares deploy with SNAPSHOT in version will use snapshot repo and without SNAPSHOT it will use staging repo. you will see it on sonatype webinterface how deployed it and when. it is still a human which closes the release and pushes it to maven-central. so all good IMO

**Comment by kares** [comment]
@mkristian agreed, still would have been confusing if you as a release manager would see two deployed artifacts in staging - one from CI and another from you running deploy.

**Comment by mkristian** [comment]
@kares agree also about the confusing bit. let me see if we can deploy on snapshots, not sure yet.

**Pull request merged**
