### PR TITLE
[travis] add --dev stage, fix JRUBY_OPTS

### PR DESCRIPTION
**Pull request by ahorek**
1/ JRUBY_OPTS are being ignored, so half of the stages aren't tested as supposed
2/ add a --dev stage in order to catch https://github.com/jruby/jruby/issues/6714

### CODE REVIEW

**Comment by headius** [comment]
Why does simply adding this to `env` not work? That seems very counter-intuitive to me.

**Comment by headius** [comment]
Looking into fixing this `getsockoptInt` thing. It appears that the non-generated logic is not using the right name for binding this method.

**Comment by ahorek** [comment]
it's a problem with thit's a problem with the order

1/ env: JRUBY_OPTS=xxx
sets the variable at the very beginning
2/ before_script: **unset JRUBY_OPTS**
which is executed after clears them

so all env options like
https://github.com/jruby/jruby/blob/ad4e8a9d0678453d5855a7f2b06cc8abc88ee82a/.travis.yml#L143
are being ignored

however, there's a probably better way how to avoid the conflicte order

**Comment by headius** [comment]
We may not need to clear it anymore. I think we started clearing it as some point because Travis was still enabling JRuby C extensions, which have not been supported since JRuby 1.6.

**Comment by ahorek** [comment]
unfortunately, the problem is still there, I tried...

**Comment by ahorek** [comment]
how about changing this
```
- name: JRuby tests jit indy jdk11
  script:
    - mvn clean package -Pbootstrap
  env: JRUBY_OPTS=-Xcompile.invokedynamic
```

to
```
- name: JRuby tests jit indy jdk11
  script:
    - export JRUBY_OPTS=-Xcompile.invokedynamic
    - mvn clean package -Pbootstrap
```
?

**Comment by headius** [comment]
@ahorek That does seem a bit better than the double env var dance. I am annoyed that we can't just set this directly in env.

**Pull request merged**
