### PR TITLE
[ci] an attempt to run tests on Windows

### PR DESCRIPTION
**Pull request by kares**
a bit of Windows CI de-ja-vu, this time trying to run `test:jruby` 
chosen JRuby suite as it is very stable, and in out control, compared to say ruby-specs

motivated by: https://github.com/jruby/jruby/issues/6322 (can re-target to `jruby-9.2` if needed)

### CODE REVIEW

**Comment by kares** [comment]
currently at: **98.8722% passed**
```
2020-07-23T14:59:21.1879431Z --------------------------------------------------------------------------------
2020-07-23T14:59:21.1880487Z 799 tests, 4434 assertions, 3 failures, 3 errors, 3 pendings, 1 omissions, 0 notifications
```

Most of the (relevant) failures are Windows compatibility bugs, but I am fine with pending those for now:
```
2020-07-23T14:58:06.5244096Z ================================================================================
2020-07-23T14:58:06.5244400Z Failure: test_stat_directory_in_jar_with_trailing_slash(TestDir)
2020-07-23T14:58:06.5244684Z D:/a/jruby/jruby/test/jruby/test_dir.rb:355:in `test_stat_directory_in_jar_with_trailing_slash'
2020-07-23T14:58:06.5244994Z      352:     assert File.exist?(source_file), "test is wrong, #{source_file} doesn't even exist"
2020-07-23T14:58:06.5245338Z      353:     assert_equal false, File.directory?(source_file)
2020-07-23T14:58:06.5245602Z      354:     assert_equal false, File.directory?(source_file + "/")
2020-07-23T14:58:06.5249688Z   => 355:     assert_raise(Errno::ENOENT) do
2020-07-23T14:58:06.5258930Z      356:       File.stat(source_file + "/")
2020-07-23T14:58:06.5259537Z      357:     end
2020-07-23T14:58:06.5267668Z      358:     source_dir = File.dirname(source_file)
2020-07-23T14:58:06.5472581Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:06.5473543Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:06.5474043Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:06.5742289Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:06.5840571Z 
2020-07-23T14:58:06.5841831Z <Errno::ENOENT> expected but was
2020-07-23T14:58:06.5842681Z <SystemCallError(<Unknown error (SystemCallError) - Unknown Error (123) - jar:file:D:/a/jruby/jruby/test/jruby/jar_with_relative_require1.jar!/test/require_relative1.rb/>)>

2020-07-23T14:58:34.1725684Z ================================================================================
2020-07-23T14:58:34.1728354Z Failure: test_ios_with_incompatible_flags(TestIO): <Errno::EINVAL> exception was expected but none was thrown.
2020-07-23T14:58:34.1732791Z D:/a/jruby/jruby/test/jruby/test_io.rb:97:in `test_ios_with_incompatible_flags'
2020-07-23T14:58:34.1746592Z       94:     # original IO
2020-07-23T14:58:34.1747324Z       95:     f = File.new(@file2, "w")
2020-07-23T14:58:34.1747783Z       96:     @to_close << f
2020-07-23T14:58:34.1771560Z   =>  97:     assert_raises(Errno::EINVAL) { IO.new(f.fileno, "r") }
2020-07-23T14:58:34.1773498Z       98:     f.close
2020-07-23T14:58:34.1775280Z       99: 
2020-07-23T14:58:34.1781057Z      100:     f = File.new(@file, "r")
2020-07-23T14:58:34.1790417Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:34.1792135Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:34.1796098Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:34.1806378Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:34.1808508Z ================================================================================

2020-07-23T14:58:34.2940083Z ================================================================================
2020-07-23T14:58:34.2940349Z Failure: test_reopen(TestIO)
2020-07-23T14:58:34.2940576Z D:/a/jruby/jruby/test/jruby/test_io.rb:145:in `test_reopen'
2020-07-23T14:58:34.2940810Z      142:     file2_fileno = file2.fileno;
2020-07-23T14:58:34.2941049Z      143:     file2 = file2.reopen(file)
2020-07-23T14:58:34.2941271Z      144:     assert_equal(file.pos, file2.pos)
2020-07-23T14:58:34.2941496Z   => 145:     assert_equal(file2_fileno, file2.fileno);
2020-07-23T14:58:34.2941721Z      146:     assert(file.fileno != file2.fileno);
2020-07-23T14:58:34.2941914Z      147:     file2.close
2020-07-23T14:58:34.2942130Z      148:     file.close
2020-07-23T14:58:34.2942349Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:34.2942572Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:34.2942788Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:34.2942998Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:34.2943207Z <3> expected but was
2020-07-23T14:58:34.2943415Z <4>
2020-07-23T14:58:34.2943635Z ================================================================================

2020-07-23T14:58:35.5389350Z ================================================================================
2020-07-23T14:58:35.5825573Z Error: test_unget_before_position_change(TestIO): IOError: byte oriented read for character buffered IO
2020-07-23T14:58:35.7342007Z org/jruby/RubyIO.java:3069:in `read'
2020-07-23T14:58:35.9200661Z org/jruby/RubyIO.java:3051:in `read'
2020-07-23T14:58:35.9754138Z D:/a/jruby/jruby/test/jruby/test_io.rb:310:in `block in test_unget_before_position_change'
2020-07-23T14:58:35.9813642Z      307:       f.read(3)
2020-07-23T14:58:35.9814310Z      308:       f.ungetc(100)
2020-07-23T14:58:35.9864250Z      309:       f.pos = 2
2020-07-23T14:58:35.9864858Z   => 310:       assert_equal("LLO", f.read(3))
2020-07-23T14:58:35.9865250Z      311: 
2020-07-23T14:58:35.9865553Z      312:       f.ungetc(100)
2020-07-23T14:58:35.9865951Z      313:       f.seek(2)
2020-07-23T14:58:35.9866233Z org/jruby/RubyIO.java:1160:in `open'
2020-07-23T14:58:35.9866531Z D:/a/jruby/jruby/test/jruby/test_io.rb:306:in `test_unget_before_position_change'
2020-07-23T14:58:35.9866831Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:35.9900120Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:35.9900493Z org/jruby/RubyKernel.java:1263:in `catch'
2020-07-23T14:58:35.9900787Z org/jruby/RubyKernel.java:1258:in `catch'
2020-07-23T14:58:35.9901085Z ================================================================================
```

let me know what you think, should we instead run bigger suites (e.g. the MRI ones) and exclude Windows failures?

**Comment by headius** [comment]
@kares I am working on Windows a bit lately and would also like to see us running the specs and MRI tests. Specs first, since we know they have been "green enough" in the past. I will play with it a bit today to see how much we need to tag to get specs running to completion.

**Comment by headius** [comment]
I have opened https://github.com/jruby/jruby/pull/6357 for Windows RubySpec fixes.

**Comment by kares** [comment]
have put the Windows failing stuff (as pending) in commit-by-commit, still I got:
`798 tests, 4430 assertions, 0 failures, 2 errors, 8 pendings, 1 omissions, 0 notifications`
and I am not really seeing those 2 errors in the [CI logs](https://github.com/jruby/jruby/runs/993348934?check_suite_focus=true#step:8:25) ... so this might need me to try running the specs on Windows, for real
:disappointed:

**Comment by kares** [comment]
was able to locate the tests failures/errors by changing test-unit to always print summary at the end, 
made it a default for all `test:jruby` runs on CI!

**Comment by headius** [comment]
I am on Windows and could give those last few items a try here. For now I'd say just mark them pending and we can get to them as soon as we have time.

**Comment by kares** [comment]
tests should be green (all failures are pended) but we still get a 1 exit status.
test-unit is only showing 1 omission and 10 pendings (no failures or errors) for the jruby suite.

**Comment by kares** [comment]
fixed the remaining Windows compatibility issues and added `mvn -P test` phase to follow `rake test:jruby`.
the commits that are worth revisiting (in terms of Windows support) are *[test] TODO: ...* prefixed.

**Comment by headius** [comment]
I believe this can be merged any time and we can investigate the pending items and TODOs from there. I think some of your fixes here may help specs so I want to land this before I tag off specs.

**Comment by headius** [comment]
I'm going to go ahead ad land #6357 as is since it makes enough fixes to get specs running to completion. I did not add a Windows target since it makes more sense for me to wait until your PR lands. Then we can collab on getting a spec run and making it greener.

**Pull request merged**
