### PR TITLE
Implement fetch for Thread.current

### PR DESCRIPTION
**Pull request by ChrisBr**
https://bugs.ruby-lang.org/issues/13009
#4876 

Tests are already implemented in ``test/mri/ruby/test_thread.rb#test_thread_local_fetch"

### CODE REVIEW

**Comment by headius** [comment]
🎉

**Comment by nomadium** [comment]
Good to see progress with more Ruby 2.5 features in JRuby although I was wondering why this PR superseded https://github.com/jruby/jruby/pull/5034 since it was almost the same change.

**Comment by ChrisBr** [comment]
@nomadium oh sorry, I missed this PR :cry:

**Comment by nomadium** [comment]
@ChrisBR No worries, I guess it was not hard to miss since there are a fair amount of open PRs.

**Pull request merged**
