### PR TITLE
Correct a format string in Signal#trap.

### LINKED ISSUE #3208: Trapping reserved signals doesn't print a meaningful message
Let's trap a reserved signal:

```ruby
trap(:ILL) {}
```

Output from MRI:

```
ArgumentError: can't trap reserved signal: SIGILL
```

Output from JRuby 9.0.0.0

```
ArgumentError: malformed format string - %S
from org/jruby/RubyString.java:1168:in `%'
```

It seems like JRuby tries to print the error, but fails for some reason.

### PR DESCRIPTION
**Pull request by Freaky**
Fixes #3208: Trapping reserved signals doesn't print a meaningful
message

### CODE REVIEW

**Comment by rtyler** [comment]
The failure below from Travis doesn't look related, but would it be possible to add a test to ensure that #3208 is really fixed?

```
     [exec] 
     [exec] Failures:
     [exec] 
     [exec]   1) FFI::Function can wrap a blocking function
     [exec]      Failure/Error: expect(Time.now - time).to be >= 2
     [exec]      NameError:
     [exec]        uninitialized constant RSpec::Matchers::BuiltIn::Be
     [exec]      # ./spec/ffi/function_spec.rb:71:in `block in (root)'
     [exec] 
     [exec] Finished in 21.64 seconds
     [exec] 4843 examples, 1 failure
     [exec] 
     [exec] Failed examples:
     [exec] 
     [exec] rspec ./spec/ffi/function_spec.rb:65 # FFI::Function can wrap a blocking function
```

**Comment by Freaky** [comment]
Certainly.  Shall I just add a new test to RubySpec?

**Comment by dirk** [comment]
@Freaky: I'm guessing it should be added to the MRI `TestSignal` test case in [this file](https://github.com/jruby/jruby/blob/master/test/mri/ruby/test_signal.rb).

**Comment by Freaky** [comment]
Did both.

**Comment by kares** [comment]
picked the fix and test as 18df48a87559c1ab07c4e8b1015575e4104e8667 and 0adaddf41ac2625853be876602593f6b645ada83 on master ... Thanks Thomas!

**Pull request closed without merging**
