### PR TITLE
[Truffle] Use Array#{max,min} from rubinius

### PR DESCRIPTION
**Pull request by brauliobo**
Java's comparable works quite differently from the <=> ruby operator

Benchmark:
```ruby
$: << '/home/braulio/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.3.0/lib'
require 'benchmark/ips'
a = [5,4,10,12,23,3,4]
Benchmark.ips do |x|
 x.config time: 5, warmup: 30
 x.report{ |t| t.times{ a.max } } 
end
```

Rubinius version:
```
Calculating -------------------------------------
                    compilation failed!?
[truffle] opt fail         now:time.rb:28 <split-12-U>                                 |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
   502,000  i/100ms
-------------------------------------------------
                    compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
     10,671k (± 20,7%) i/s -     50,200k
```

Original version:
```
Calculating -------------------------------------
                    compilation failed!?
[truffle] opt fail         match_io:slex.rb:203                                        |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         match_io:slex.rb:203                                        |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         now:time.rb:28 <split-0-U>                                  |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
compilation failed!?
[truffle] opt fail         job.rb:235<OSR>                                             |Reason java.lang.StackOverflowError 
   403,000  i/100ms
-------------------------------------------------
                         10,568k (± 18,7%) i/s -     49,972k
```

### CODE REVIEW

**Comment by brauliobo** [comment]
I have used `git-new-workdir` for using both branches simultaneously. I think it is ok as they will different target folders, right?

**Comment by chrisseaton** [comment]
I'm waiting on some other changes to be checked carefully for performance regression before I try applying this. Running all of our benchmarks takes a while.

**Comment by brauliobo** [comment]
@chrisseaton i'll try this on truffle-head as soon as possible, maybe the errors are different there.

**Comment by eregon** [comment]
`block_given?` is likely a killer here too.

**Comment by brauliobo** [comment]
@eregon yeah, pretty poor implementation, it calls block_given? for each element.

but yet we need a proof that it is slower

```ruby
  def max
    max = undefined
    each do
      o = Rubinius.single_block_arg
      if undefined.equal? max 
        max = o 
      else
        comp = block_given? ? yield(o, max) : o <=> max 
        unless comp
          raise ArgumentError, "comparison of #{o.class} with #{max} failed"
        end 

        if Comparable.compare_int(comp) > 0 
          max = o 
        end 
      end 
    end 

    undefined.equal?(max) ? nil : max 
  end 
```

**Comment by eregon** [comment]
@brauliobo the real problem is that `block_given?` needs to get the caller frame currently to know if that frame has a block, and that iterates the stack and deoptimizes, which is not fast.
We should be able to move the check out of the loop or at least make it very cheap once we have fast access to the caller frame.

**Comment by thedarkone** [comment]
(off topic to this PR)

@eregon is it forever game over for methods containing `block_given?`, or is this a temporary truffle/graal/jruby deficiency?

**Comment by chrisseaton** [comment]
We have an optimisation in mind to fix `block_given?` by supplying a direct reference to the caller frame when calling some methods, so one does not have to be found by walking the stack. This will allow references to local variables and things like the block in the caller frame to be constant folded, which is what `block_given?` needs. This will also allow us to do some mind-bending constant folding such as `binding_of_caller.local_variable_get(:x) * y`.

The optimisation is simple but will require a bit of refactoring. We should get around to it.

**Comment by chrisseaton** [comment]
`block_given?` was fixed. It might be time to try this again. @brauliobo would you like me to show you how to test if this now performs as well without the Java code? Or if you aren't interested in that I'll do it myself.

**Comment by brauliobo** [comment]
@chrisseaton will do some benchmarks asap

**Comment by chrisseaton** [comment]
@brauliobo do you want us to take another look at this PR? If you update it to latest JRuby we'll help you run the benchmarks and see if it needs any more work before it can be merged.

**Comment by brauliobo** [comment]
yes @chrisseaton please, really would like to look into this into this but time is running away. thank you :)

**Comment by chrisseaton** [comment]
Sorry, not sure what you mean. Do you mean you don't have time at the moment, but will do soon? Or you're unlikely to have time to do this any time soon so we should do it?

**Comment by brauliobo** [comment]
it is better that you do it because being realistic I won't have enough time for this.
thanks for the good job with jruby truffle :)

**Comment by brauliobo** [comment]
Original version (current master):
```
Warming up --------------------------------------
                         2,187M i/100ms
Calculating -------------------------------------
                         52,145M (± 19,0%) i/s -    203,355M in   5,006412s
```
Ruby version:
```
Warming up --------------------------------------
                         2,163M i/100ms
Calculating -------------------------------------
                         54,980M (± 18,4%) i/s -    212,020M in   4,998354s
```

**Comment by chrisseaton** [comment]
Looks great! I'm just setting up a new internal CI and benchmarking system, which I'd like to run this on to give us some more confidence, so I'm sorry I'll just need to delay you by a week or so before we can merge this.

**Comment by chrisseaton** [comment]
I'm also going to set up some things called PE tests - I'll get back to you about those.

**Comment by brauliobo** [comment]
benchmark used:
```ruby
$: << '/home/braulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/benchmark-ips-2.6.1/lib'                                                                                                 
require 'benchmark/ips'                                                                                                                                                                      
a = [5,4,10,12,23,3,4]                                                                                                                                                                       
Benchmark.ips do |x|                                                                                                                                                                         
  x.config time: 5, warmup: 30                                                                                                                                                               
  x.report{ |t| t.times{ a.max } }                                                                                                                                                           
end                                                                                                                                                                                          
```

**Comment by brauliobo** [comment]
@chrisseaton updated the benchmarks after doing two separate builds for each branch using `git-new-workdir` to ensure everything is correct. now the ruby version appears to be a bit slower

**Comment by chrisseaton** [comment]
We should revisit now our benchmarks are stable again after some changes to Graal.

**Comment by brauliobo** [comment]
Apparently Graal can't optimize constants correctly with the ruby code.
master version:
```
~/P/j/j/master git:master ❯❯❯ JAVACMD=~/Projects/jruby/graal/graalvm-0.16-dev-dk/bin/java bin/jruby -X+T ../bench.rb
Warming up --------------------------------------
                    2068814,000M i/100ms
Calculating -------------------------------------
                     8843082613733733,000M (±1289068246665058,0%) i/s - 386868218,000M in 5010767353050232,000000s
```
ruby version:
```
~/P/j/j/max git:test-array-max-min ❯❯❯ JAVACMD=~/Projects/jruby/graal/graalvm-0.16-dev-dk/bin/java bin/jruby -X+T ../bench.rb
Warming up --------------------------------------
                    2032078,000M i/100ms
Calculating -------------------------------------
                     8675873750696292,000M (±12919911379646804,0%) i/s - 390158976,000M in 5016019309898376,000000s
```
Performance is roughly the same with constants.

**Comment by chrisseaton** [comment]
What's going on with those numbers? `8675873750696292,000M`, `±12919911379646804,0%`, `5016019309898376,000000s`.

**Comment by chrisseaton** [comment]
Also, I think ironically MRI now has separate methods for `Array#min` and `Enumerable#min`, but that's a problem we can solve later if we merge this now.

**Comment by brauliobo** [comment]
Using a slightly different script of a randomly generated array:
```ruby
$: << '/home/braulio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/benchmark-ips-2.6.1/lib'
require 'benchmark/ips'
a = 10.times.map{ rand(1..20) }
Benchmark.ips do |x|
  x.config time: 5, warmup: 30
  x.report{ |t| t.times{ a.max } }
end
```
Makes the java version perform a bit faster:
```
~/P/j/j/master git:master ❯❯❯ JAVACMD=~/Projects/jruby/graal/graalvm-0.16-dev-dk/bin/java bin/jruby -X+T ../bench-rand.rb                                                                  ◼
Warming up --------------------------------------
                    2005529,000M i/100ms
Calculating -------------------------------------
                     8165281379313222,000M (±15329656650549875,0%) i/s - 346956517,000M in 5012463420974732,000000s
```
```
~/P/j/j/max git:test-array-max-min ❯❯❯ JAVACMD=~/Projects/jruby/graal/graalvm-0.16-dev-dk/bin/java bin/jruby -X+T ../bench-rand.rb
Warming up --------------------------------------
                    197074,000M i/100ms
Calculating -------------------------------------
                     7037981787634672,000M (±1561739903804728,0%) i/s - 30152322,000M in 5004666628997803,000000s
```

**Comment by brauliobo** [comment]
@chrisseaton good question about the number, do you recommend something besides `benchmark-ips`?

**Comment by brauliobo** [comment]
upgraded to benchmark-ips 2.7.2 and still get the same weird numbers

**Comment by chrisseaton** [comment]
`benchmark-ips` is excellent - but something is clearly wrong with `5012463420974732,000000s` - that's 158 thousand milena of benchmarking time you've done there!

**Comment by chrisseaton** [comment]
I'll pull locally and try tomorrow, and I'll run against out internal CI system as well. I'll update tomorrow.

**Comment by chrisseaton** [comment]
It looks like this applied cleaning this time and didn't have any impact on performance. Sorry it took a year to get that in! We had the issue with `block_given?` which required some innovation, and then our benchmarks were a bit all over the place for a while so we couldn't see if it was safe to apply. Thanks!

**Comment by chrisseaton** [comment]
The final commit applying it is https://github.com/jruby/jruby/commit/d7ca7b747a6e424e231c263dc94af8535d72406c

**Pull request closed without merging**
