### PR TITLE
[Truffle] Adding Long Integer specialization for Fixnum coerce

### PR DESCRIPTION
**Pull request by bjfish**

### CODE REVIEW

**Comment by bjfish** [comment]
@nirvdrum Does this look right?

**Comment by eregon** [comment]
Looks good!

**Comment by nirvdrum** [comment]
This looks good.  You might want to handle the `BigInteger` case as well just to round it out.  Rubinius handles `Fixnum` and `Bignum`.  I don't see where the `String` and coercible variants come from.  I'll have to ask @chrisseaton about that.

**Comment by eregon** [comment]
Yes, there should really not be a `String` case, but maybe Rubinius code requires it?

**Comment by eregon** [comment]
Removed the `String` and `to_f` cases, they are handled by `Numeric#coerce`.

**Comment by eregon** [comment]
And Bignum is not handled specially in MRI, so let's keep it as is.
```ruby
> 2.coerce (1<<75)
=> [3.777893186295716e+22, 2.0]
```

**Pull request merged**
