### PR TITLE
Remove stale rubyspec tags

### PR DESCRIPTION
**Pull request by etehtsea**

### CODE REVIEW

**Comment by kares** [comment]
module specs and an io spec seems to fail : 
```
     [exec] 1)
     [exec] IO#each with limit when limit is 0 raises an ArgumentError FAILED
     [exec] Expected ArgumentError but no exception was raised (#<IO:0xa54c14d> was returned)
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/io/shared/each.rb:77:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:1667:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1589:in `all?'
     [exec] org/jruby/RubyFixnum.java:299:in `times'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/io/each_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:974:in `load'
     [exec] org/jruby/RubyBasicObject.java:1667:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] 
     [exec] 2)
     [exec] Numeric#% returns self - other * self.div(other) ERROR
     [exec] NoMethodError: undefined method `%' for #<NumericMockObject:0x103560e1 @null=nil, @name="self">
     [exec] org/jruby/RubyBasicObject.java:1633:in `method_missing'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/numeric/modulo_spec.rb:14:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:1667:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1589:in `all?'
     [exec] org/jruby/RubyFixnum.java:299:in `times'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/numeric/modulo_spec.rb:22:in `<main>'
     [exec] org/jruby/RubyKernel.java:974:in `load'
     [exec] org/jruby/RubyBasicObject.java:1667:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] 
     [exec] 3)
     [exec] An exception occurred during: Mock.verify_count
     [exec] Numeric#% returns self - other * self.div(other) FAILED
     [exec] Mock 'self' expected to receive 'div' exactly 1 times but received it 0 times
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] org/jruby/RubyHash.java:1344:in `each'
     [exec] org/jruby/RubyBasicObject.java:1667:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1589:in `all?'
     [exec] org/jruby/RubyFixnum.java:299:in `times'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/numeric/modulo_spec.rb:22:in `<main>'
     [exec] org/jruby/RubyKernel.java:974:in `load'
     [exec] org/jruby/RubyBasicObject.java:1667:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1734:in `each'
```
... also did you test this on Windows (since you removed some windows: tagged) ?

**Comment by etehtsea** [comment]
@kares This is strange, because actually `mspec tag --purge` should remove tags that don't match any specs anymore.

```
       --purge                Remove all tags not matching any specs
```

@eregon could you please help, maybe I got it wrong.

**Comment by etehtsea** [comment]
@kares okay, I left windows tags intact, because I couldn't run specs on windows (I tried but all tasks failed with various errors).

**Comment by headius** [comment]
Wow...I love to see tags go away :-) Once this runs green we'll merge. Thanks for restoring the Windows tags.

**Comment by etehtsea** [comment]
@headius travis is green

**Comment by headius** [comment]
Thank you!

**Pull request merged**
