### PR TITLE
Another fix for #5418

### PR DESCRIPTION
**Pull request by enebo**

### CODE REVIEW

**Comment by kares** [comment]
@enebo I am noticing this one as a regression, that likely only reproduces with some ENVs

here's my failing test, since this has been merged, its all green a commit before that : 
```
kares@clevo:~/workspace/oss/jruby$ bin/jruby -Itest test/jruby/test_date.rb 
/home/kares/workspace/oss/jruby/lib/ruby/stdlib/power_assert.rb:7: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
Loaded suite test/jruby/test_date
Started
....................................F
=============================================================================================================================================================================================================
Failure: test_time_conv(TestDate)
test/jruby/test_date.rb:565:in `test_time_conv'
     562:   def test_time_conv
     563:     today = Date.today
     564:     assert_equal(today.to_s, Date.today.to_time.strftime('%F'))
  => 565:     assert_equal(today, Date.today.to_time.to_date)
     566: 
     567:     time = DateTime.now
     568:     #assert_equal(nil, time.to_time.zone)
<#<Date: 2019-01-27 ((2458510j,0s,0n),+0s,2299161j)>> expected but was
<#<Date: 2019-01-27 ((2458511j,0s,0n),+0s,2299161j)>>

diff:
? #<Date: 2019-01-27 ((2458510j,0s,0n),+0s,2299161j)>
?                            1                       
=============================================================================================================================================================================================================
........

Finished in 0.704371 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
45 tests, 1073 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.7778% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
63.89 tests/s, 1523.34 assertions/s

```

**Comment by kares** [comment]
and just for the record this passes fine on the CI (at UTC) ... my local-time is CET (GMT+1)

**Comment by enebo** [comment]
@kares bummer...yeah I wonder if we can see n different timezone also not work or if this is some singular problem?

**Comment by kares** [comment]
> wonder if we can see n different timezone also not work or if this is some singular problem?

do not know but it seems I am getting 1 day off with this change.
it's kind of similar (inverse?) to how https://github.com/jruby/jruby/issues/5418 is a problem for `-0600` (wout this patch)

**Pull request merged**
