### PR TITLE
[embed] refactor (JSR223) exception wrapping

### PR DESCRIPTION
**Pull request by kares**
seems it's been a while since this code was visited, there's some cleanup/refactoring along the line.

the motivation is trying to use `javax.script` APIs and finding things a bit cumbersome, namely:
- Ruby raises get double packed into an "embed failed exception" which than is wrapped into a `javax.script.ScriptException` (when using `ScriptEngine#invokeMethod`),
  believe this is just ineffective - e.g. Nashorn actually [exports](https://docs.oracle.com/javase/8/docs/jdk/api/nashorn/jdk/nashorn/api/scripting/NashornException.html) it's specific exceptions and doesn't always wrap.
 JRuby, since 9.2, has the Java chain for Ruby exceptions - which is very useful with JSR223 (unless it's burried to causes down the line), JRuby should really consider doing a breaking change here ... as proposed.

  also, any throwable gets wrapped (into a `InvokeFailedException`) even `java.lang.Error`s, which feels weird.
- null returns around JRuby's JSR-223 script engine impl, e.g. it was legit to `callMethod("", foo)`with an empty name that pretty much doesn't actually invoke a Ruby method - the impl simply returned null (and this was actually tested :gun:).

- (silent) exception printout(s) and runtime std-out printing ruby exceptions by in embed mode

**CHANGE SUMMARY:**
- javax.script embed APIs will no longer wrap with intermediate `InvokeFailedException`, `RaiseException`s will simply by wrapped one level into a (checked) `javax.script.ScriptException`
- `ScriptingContainer` continues to use the embed exception wrapping by default, but there's a way to disable wrapping using the added constructor
- "breaking change": only `java.lang.Exception` types will be wrapped - never `java.lang.Error` regardless of whether it's coming from a Ruby raise (no way to detect)

~~Potential Open Questions~~: 
- ~~do we want to keep `org.jruby.embed.InvokeFailedException` **deprecated** given ScriptingContainer will still wrap into those by default~~
- ~~maybe a better `ScripingContainer` API is needed e.g. factory methods where we always turn off wrapping by default (esp. if we keep `InvokeFailedException` deprecated)~~

### CODE REVIEW

**Comment by headius** [comment]
Pre-review comments...

> do we want to keep org.jruby.embed.InvokeFailedException deprecated

Since this is still used by default in ScriptingContainer invokes I think we probably can't deprecate it unless we also deprecate the invoke paths that use it. This leads to the second question...

> maybe a better ScripingContainer API is needed

I am less excited about adding to the factory API than I would be about deprecating current invoke/eval methods in favor of new ones. Those eval methods have not been touched in over a decade and there are better forms of invoke and eval we could add as a new API. That would allow us to deprecate the old paths and provide a migration path away from old patterns.

For purposes of this PR, which mainly seeks to reduce the wrapping happening inside the javax.script API, I would say let's **not** deprecate InvokeFailedException until we can work on making a new ScriptingContainer API that doesn't use it at all.

**Comment by kares** [comment]
still find some (untested) cases related to exceptions - there is proper `javax.script.ScriptException` wrapping around `eval`
but not if a script got "pre-compiled" using `((Compilable) engine).compile("...");` (e.g. in case of a syntax error the non-wrapped exception was thrown previously), should be fixed and properly tested ...

**Comment by kares** [comment]
:green_circle: after merge, note that the PR does NOT resolve https://github.com/jruby/jruby/issues/5876 but we at least explicitly test existing behaviour with compiled scripts.

**Comment by headius** [comment]
This can be merged any time and I will look into enhancing the 223 exception messages with file and line info once it has landed (#6560).

**Pull request merged**
