### PR TITLE
Update jnr-constants for fixes after the updated generation logic

### LINKED ISSUE #1509: Socket::Constants incorrect on Windows
```
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> Socket::Constants::AF_INET
=> 4
irb(main):003:0> Socket::Constants::AF_INET6
=> 33
irb(main):004:0> RUBY_DESCRIPTION
=> "jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) Client VM 1.7.0_07-b10 [Windows 7-x86]"
irb(main):005:0>
```

According to [MSDN](http://msdn.microsoft.com/en-us/library/windows/desktop/ms737530%28v=vs.85%29.aspx) values should be
- Socket::Constants::AF_INET == 2
- Socket::Constants::AF_INET6 == 23

### PR DESCRIPTION
**Pull request by headius**
Thanks to @ahorek for help getting these regenerated.

### CODE REVIEW

**Comment by ahorek** [comment]
these tests should be updated
https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/test/jruby/test_system_error.rb#L8
and
https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/core/src/main/java/org/jruby/RubySystemCallError.java#L37

some failures are probably related to missing "O_TMPFILE"
https://github.com/jnr/jnr-constants/pull/46/files#diff-9aec806eac834c0d9bbc7ad7d3bfb024R25

maybe related?
https://github.com/jcupitt/libvips/issues/922#issuecomment-377507947
http://lists.busybox.net/pipermail/buildroot/2016-August/171072.html

**Comment by ahorek** [comment]
also after this change I have a strange error on windows (master https://github.com/jruby/jruby/commit/7ea28954e0fd4e3f96600dffe5f74e437a8fb5e9 works)

reproduction
```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
end
```

```
Fetching git://github.com/rails/rails.git

Retrying `git clone "git://github.com/rails/rails.git" "/jruby/lib/ruby/gems/shared/cache/bundler/git/rails-16a5e918a06649ffac24fd5873b875daf66212ad" --bare --no-hardlinks --quiet` due to error (2/4): ArgumentError wrong number of arguments (1 for 0)
Retrying `git clone "git://github.com/rails/rails.git" "/jruby/lib/ruby/gems/shared/cache/bundler/git/rails-16a5e918a06649ffac24fd5873b875daf66212ad" --bare --no-hardlinks --quiet` due to error (3/4): ArgumentError wrong number of arguments (1 for 0)
Retrying `git clone "git://github.com/rails/rails.git" "/jruby/lib/ruby/gems/shared/cache/bundler/git/rails-16a5e918a06649ffac24fd5873b875daf66212ad" --bare --no-hardlinks --quiet` due to error (4/4): ArgumentError wrong number of arguments (1 for 0)
ArgumentError: wrong number of arguments (1 for 0)
                          ` at uri:classloader:/jruby/kernel/jruby/process_manager.rb:28
                          ` at uri:classloader:/jruby/kernel/jruby/process_manager.rb:50
                        git at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:171
  capture_and_filter_stderr at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:249
                       open at org/jruby/ext/tempfile/Tempfile.java:260
  capture_and_filter_stderr at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:247
                        git at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:171
         with_clean_git_env at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/shared_helpers.rb:83
                        git at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:170
                  git_retry at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:162
                        run at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/retry.rb:40
                    attempt at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/retry.rb:30
                  git_retry at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:161
                   checkout at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git/git_proxy.rb:103
                      fetch at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git.rb:303
                      specs at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/source/git.rb:161
      converge_locked_specs at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/definition.rb:754
                       each at org/jruby/RubyArray.java:1802
      converge_locked_specs at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/definition.rb:740
                    resolve at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/definition.rb:248
                      specs at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/definition.rb:171
          resolve_remotely! at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/definition.rb:159
          resolve_if_needed at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/installer.rb:287
                        run at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/installer.rb:83
                       lock at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/process_lock.rb:12
                       open at org/jruby/RubyIO.java:1154
                       lock at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/process_lock.rb:9
                        run at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/installer.rb:72
                    install at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/installer.rb:25
                    gemfile at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/inline.rb:62
                  temporary at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/settings.rb:136
                    gemfile at /jruby/lib/ruby/gems/shared/gems/bundler-1.16.5/lib/bundler/inline.rb:61
                     <main> at inline.rb:3
```

**Comment by headius** [comment]
> these tests should be updated

I just removed it. It wasn't a large test and there's considerably better coverage for system errors elsewhere.

> some failures are probably related to missing "O_TMPFILE"

I've just pushed jnr/jnr-constants@6539638 which adds _GNU_SOURCE for OpenFlags, but I wonder if there's a better way to isolate this per env (without having "if Linux..." all over the generator files).

I'll update OpenFlags and see if it helps.

**Comment by headius** [comment]
I went ahead with the merge.

Master went red with my O_CLOEXEC tweak...but only because it had the wrong O_CLOEXEC for Linux. That's resolved by this PR, so it should pass fine now. 🤞

**Pull request merged**
