### PR TITLE
support (seekable) ByteArrayInputStream#to_io.rewind

### PR DESCRIPTION
**Pull request by kares**
except `FileInputStream` it seems quite useful to be able to rewind/seek a `byte[]` backed stream

this is not possible using `Channels.newChannel` as the returned channel (except for files) is not seekable
but using the 9K refactored RubyIO its fairly easy to play a trick by returning a custom channel instance ...

1.7.x remains behaving weirdly on `rewind` ... more notes at #2381

### CODE REVIEW

**Comment by headius** [comment]
@kares I appreciate the attribution but the code at https://github.com/jruby/jruby/commit/6142ea3c062761bf9d8c926487a46b578aad4f58#diff-b60adbaec9c15033c4eb0231a09d211aR46 worries me. We can't incorporate code from GPL codebases like this, even if they're been massaged into place a little.

I'd suggest you look at the Android implementation of this logic, which is licensed Apache-2.0. We can incorporate them into a separate file with an Apache license header and it should be compatible with all three of our licenses.

Here's the Android 4.3 impl of Channels at equivalent read method: https://android.googlesource.com/platform/libcore/+/android-4.3_r1/luni/src/main/java/java/nio/channels/Channels.java#297

**Comment by kares** [comment]
@headius thanks, the problematic part is now re-implemented as suggested.
tests fail due missing jnr-posix SNAPSHOT (currently, there's no green travis-ci build to rebase this off).

**Comment by headius** [comment]
@kares I'll pull it down today, review and make sure it's building, and push it out.

**Comment by headius** [comment]
Testing seems fine, I'll push shortly.

Last suggestions, if you get a chance (just throw them on master):

* Try to grab and setAccessible the fields you access during static initialization; if we can't do it, we need to fall back to the unseekable wrapper.
* Saving the fields will also be better perf rather than looking up and hitting setAccessible every time they're accessed.

**Pull request merged**
