### PR TITLE
upgrade mavengem extension

### PR DESCRIPTION
**Pull request by mkristian**
@kares in case I do not get this merged today please feel free to merge - if CI says OK of course ;)

### CODE REVIEW

**Comment by headius** [comment]
Weird error killed all the builds:

```
org.apache.maven.InternalErrorException: Internal error: org.jruby.embed.InvokeFailedException: (SyntaxError) /home/travis/build/jruby/jruby/lib/pom.rb:77: syntax error, unexpected tIDENTIFIER
  repository :id => :mavengems, :url => 'mavengem:https://rubygems.org'
```

You didn't even change that line 😢

**Comment by headius** [comment]
Oh I see...missed that the builds ran before the most recent commit 👍

**Comment by headius** [comment]
Looks good!

**Comment by kares** [comment]
will rebase https://github.com/jruby/jruby/pull/5340 too see how its going on CI

**Comment by headius** [comment]
It's working for me now, suddenly. Are there some soft-version dependencies in the chain perhaps, allowing it to pick up an older version before artifacts propagate?

**Pull request merged**
