### PR TITLE
New readme

### PR DESCRIPTION
**Pull request by chrisseaton**
I thought I could make some positive changes to the readme:

* Talk about it being a JVM implementation rather than a Java implementation
* Building instructions are all available in BUILDING.md so just point people there
* Provide instructions on how to install without building from source
* Warn people against using old versions from their package manager
* Add some positive statements about what we are trying to achieve
* Remove some dead links

What do people think?

### CODE REVIEW

**Comment by cheald** [comment]
First off: It's strangely hilarious to me that this failed the CI build :)

That said, I like the direction. I might almost go a step further and go out of the way to highlight some of the reasons that you might want to use JRuby over MRI, rather than just casually mentioning them in the "about" section. The README is what people see when they first encounter the project, so it should really be half information, half marketing copy, IMHO. 

I would also include information on bug reporting procedures, pull request protocol, and maybe even a link to the mailing list and IRC channel.  If someone has a problem with it, they shouldn't need to go further than the README to figure out how to get additional help.

**Comment by chrisseaton** [comment]
Yeah, introducing some form of marketing copy was my goal. I think the current version isn't confident enough, if you see what I mean.

**Comment by kares** [comment]
:+1:

**Comment by donv** [comment]
:+1:

**Comment by headius** [comment]
This was in pre2 bundle, so marking for pre2.

**Pull request merged**
