### PR TITLE
[Truffle] Adding progress on Array#[]=.

### PR DESCRIPTION
**Pull request by bjfish**
I’ll be working on getting more of these specs passing.

### CODE REVIEW

**Comment by chrisseaton** [comment]
This caused at least one failure (benchmarks still running), in fannkuch-redux.

```
jruby: using Graal Truffle Runtime
/home/slave/slaves/slave0/slave/buildlog/jruby-bench-jruby_truffle-release_sunfire/ruby-benchmarks/lib/bench/benchmarks/classic/fannkuch-redux.rb:51:in `[]=': internal implementation error - ArrayIndexOutOfBoundsException null java.lang.System.arraycopy(Native Method) (RubyTruffleError)
  from /home/slave/slaves/slave0/slave/buildlog/jruby-bench-jruby_truffle-release_sunfire/ruby-benchmarks/lib/bench/benchmarks/classic/fannkuch-redux.rb:51:in `fannkuch'
  from /home/slave/slaves/slave0/slave/buildlog/jruby-bench-jruby_truffle-release_sunfire/ruby-benchmarks/lib/bench/benchmarks/classic/fannkuch-redux.rb:104:in `harness_sample'
  from /home/slave/slaves/slave0/slave/buildlog/jruby-bench-jruby_truffle-release_sunfire/ruby-benchmarks/lib/bench/../bench/harness.rb:38:in `<main>'
  from /home/slave/slaves/slave0/slave/buildlog/jruby-bench-jruby_truffle-release_sunfire/ruby-benchmarks/lib/bench/benchmarks/classic/fannkuch-redux.rb:111:in `<main>'
```

You can test this locally by doing `jt debug classic-fannkuch-redux`. Can you take a look?

**Comment by bjfish** [comment]
@chrisseaton yeah i can take a look

**Comment by bjfish** [comment]
@chrisseaton happen to know how to resolve this bench error?
```
Brandons-MacBook-Pro:jruby-mine brandonfish$ jt bench debug classic-fannkuch-redux
bash -c "JAVACMD=/Users/brandonfish/Downloads/graalvm-jdk1.8.0/bin /Users/brandonfish/Documents/jruby-mine/bin/jruby -J-Xmx2G -J-d64 -J-server -J-G:+TruffleCompilationExceptionsAreFatal -X+T -I/Users/brandonfish/Documents/bench9000/lib/bench/..  /Users/brandonfish/Documents/bench9000/lib/bench/benchmarks/classic/fannkuch-redux.rb"
/Users/brandonfish/Documents/jruby-mine/bin/jruby: line 393: /Users/brandonfish/Downloads/graalvm-jdk1.8.0/bin: is a directory
/Users/brandonfish/Documents/jruby-mine/bin/jruby: line 393: exec: /Users/brandonfish/Downloads/graalvm-jdk1.8.0/bin: cannot execute: Undefined error: 0
/Users/brandonfish/Documents/bench9000/lib/bench/implementation.rb:42:in `block in measure': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Users/brandonfish/Documents/bench9000/lib/bench/implementation.rb:37:in `popen'
	from /Users/brandonfish/Documents/bench9000/lib/bench/implementation.rb:37:in `measure'
	from /Users/brandonfish/Documents/bench9000/lib/bench/main.rb:215:in `block (2 levels) in main'
	from /Users/brandonfish/Documents/bench9000/lib/bench/main.rb:208:in `each'
	from /Users/brandonfish/Documents/bench9000/lib/bench/main.rb:208:in `block in main'
	from /Users/brandonfish/Documents/bench9000/lib/bench/main.rb:207:in `each'
	from /Users/brandonfish/Documents/bench9000/lib/bench/main.rb:207:in `main'
	from /Users/brandonfish/Documents/bench9000/bin/bench:13:in `<main>'
FAILED (pid 49312 exit 1): {"JRUBY_9000_DEV_DIR"=>"/Users/brandonfish/Documents/jruby-mine", "GRAAL_BIN"=>"/Users/brandonfish/Downloads/graalvm-jdk1.8.0/bin", "JRUBY_OPTS"=>"-J-G:+TraceTruffleCompilation -J-G:+DumpOnError"} ruby -I/Users/brandonfish/Documents/bench9000/lib /Users/brandonfish/Documents/bench9000/bin/bench score jruby-9000-dev-truffle-graal --show-commands --show-samples classic-fannkuch-redux
Brandons-MacBook-Pro:jruby-mine brandonfish$ 
```

**Comment by chrisseaton** [comment]
Is this still a problem? I saw the PR to fix fannkuch.

**Comment by bjfish** [comment]
@chrisseaton I fixed fannkuch but never got `jt bench debug classic-fannkuch-redux`  command to work. I'll take a look at running this command  later on.

**Pull request merged**
