### PR TITLE
Default "first" item is "true" in ProfilePrinter

### PR DESCRIPTION
**Pull request by kml**
fixes many spec:profiler errors
bacports parts of https://github.com/jruby/jruby/commit/f1eab903b967c8e6b7a0859437c9ecf5d177788d

### CODE REVIEW

**Comment by kares** [comment]
@BanzaiMan ... could you please provide some notes on closing PR(s)? 
... this might have made some sense esp. since its a [backport from master](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/runtime/profile/builtin/ProfilePrinter.java#L101)

**Comment by kml** [comment]
https://github.com/jruby/jruby/blame/jruby-1_7/core/src/main/java/org/jruby/runtime/profile/builtin/ProfilePrinter.java#L101
https://github.com/jruby/jruby/commit/63aeef6f367225dca0b2b7751459e7b51e3c7e24

**Comment by headius** [comment]
Yes, was this closed in error?

**Comment by kml** [comment]
It's OK that is closed.
It looks that its already bacported to jruby-1_7 in linked commits

**Pull request closed without merging**
