### PR TITLE
Implement hash cache to fix #5280

### LINKED ISSUE #5280: bundle install fails since #5215
### Environment

* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
```
$ jruby -v
jruby 9.2.1.0-SNAPSHOT (2.5.0) 2018-07-31 cbccb8d Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 [linux-x86_64]
```

* Operating system and platform (e.g. `uname -a`)

```
$ uname -a
Linux li1554-157.members.linode.com 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Other relevant info you may wish to add:
* Installed or activated gems - Rails
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables
```ruby
$ env |grep RUBY
JRUBY_OPTS=--dev -J-Xmx2048M
RUBY_CONFIGURE_OPTS=--disable-install-doc
```

### Steps to reproduce

* Create `Gemfile`

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rails"
```

* Execute `gem install bundler`

```ruby
$ gem install bundler
```
* Execute `bundle install`

```ruby
$ bundle install
```

### Expected Behavior
Bundle should pass.

### Actual Behavior

```
NoMethodError: undefined method `dep' for #<Gem::Dependency:0x100c8b75>
Did you mean?  dup
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/dep_proxy.rb:18:in `=='
  org/jruby/ext/set/RubySet.java:639:in `add?'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/spec_set.rb:27:in `block in for'
  org/jruby/RubyKernel.java:1412:in `loop'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/spec_set.rb:25:in `for'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/definition.rb:810:in `converge_locked_specs'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/definition.rb:248:in `resolve'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/definition.rb:204:in `missing_specs'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/definition.rb:209:in `missing_specs?'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/installer.rb:284:in `resolve_if_needed'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/installer.rb:83:in `block in run'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/process_lock.rb:12:in `block in lock'
  org/jruby/RubyIO.java:1154:in `open'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/process_lock.rb:9:in `lock'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/installer.rb:72:in `run'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/installer.rb:25:in `install'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/cli/install.rb:65:in `run'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/cli.rb:224:in `block in install'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/settings.rb:136:in `temporary'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/cli.rb:223:in `install'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/exe/bundle:30:in `block in <main>'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /home/yahonda/git/jruby/lib/ruby/gems/shared/gems/bundler-1.16.3/exe/bundle:22:in `<main>'
  org/jruby/RubyKernel.java:997:in `load'
  /home/yahonda/git/jruby/bin/bundle:1:in `<main>'
```

### PR DESCRIPTION
**Pull request by ChrisBr**
This will fix https://github.com/jruby/jruby/issues/5280 as we only use eql? now on a bin and hash collision. Before we didn't check the hash as we did not store it. This will restore similar behavior before the new hash implementation.

### CODE REVIEW

**Comment by ChrisBr** [comment]
Ok, CI looks quite good :+1:

**Comment by eregon** [comment]
@ChrisBr Hello!

I beg to differ about the CI, because ruby/spec seem to get stuck after this change, see https://travis-ci.org/jruby/jruby/builds/419737258?utm_source=github_status&utm_medium=notification
I can also replicate locally with:
```
bin/jruby spec/mspec/bin/mspec run -fs -Gfails -Gcritical -Gslow spec/ruby/library/set
```

Reverting this PR with:
```
git revert -m 1 067b279320863654c3dc2af217a5d7165b4ef915
```
Allows those specs to pass.

**Comment by ahorek** [comment]
I think https://github.com/jruby/jruby/pull/5278 should fix it, but there's a conflict @ChrisBr ?

**Comment by ChrisBr** [comment]
@eregon hope you had safe travels back from EuRuKo! Thanks for the report, I will look into it

**Comment by ChrisBr** [comment]
@eregon I can not reproduce with 
``
bin/jruby spec/mspec/bin/mspec run -fs -Gfails -Gcritical -Gslow spec/ruby/library/set
``

on current master...

But as this is related to Set, I could imagine that it might be related to

https://github.com/jruby/jruby/pull/5278/commits/755ccdb8295fd1702f83a4109f18517a577eaa89

as if the hash gets initialized with a non pow of two size, the secondary hash function is not a generator and therefore could end in an infinite loop. It could never reproduce this but it could be theoretically possible. 

Could you please try to reproduce with this PR: https://github.com/jruby/jruby/pull/5278 ?

**Comment by eregon** [comment]
@ChrisBr Odd, I can reproduce consistently on current master (067b279320863654c3dc2af217a5d7165b4ef915) with that command.

Using the latest commit of #5278 (6d44f80eff8c1fc47aea45b3437e0ebae9f869af) seems to fix it, so let's merge that :)

Hope you had safe travels back too from EuRuKo :)

**Comment by ahorek** [comment]
probably the same problem on current master
```
gem install mime-types
irb
require 'mime-types'
```
-> hangs

#5278 (6d44f80) works

**Comment by eregon** [comment]
@ChrisBr I merged #5278, thanks for the quick fix :)

**Comment by ChrisBr** [comment]
@ahorek @eregon cool, thanks :+1:

**Pull request merged**
