### PR TITLE
public org.jruby.Runtime.Profile.Builtin::MethodData

### PR DESCRIPTION
**Pull request by kml**
this makes building custom tooling easier

http://pastebin.com/XhNYdMtD

### CODE REVIEW

**Comment by kml** [comment]
Thanks to changing visiblity I can compile my modified copies of all default ProfilePrinters.
If it does not make sense to accept all those changes please ignore the PR.

**Comment by kares** [comment]
originally those package-protected classes were hidden on purpose as they were not polished. 
but assuming no API review is about to happen soon its probably fine ... as a semi-official API :)

**Comment by headius** [comment]
@kares was this closed by mistake?

**Comment by kares** [comment]
@headius seems like it might have been ... re-opening (@BanzaiMan feel free to close with feedback)

**Comment by kml** [comment]
From my perspective I don't need this right now.
I've done profiling using patched version of jruby and I'm not sure if anyone else need it.

**Comment by kares** [comment]
these are still valid (even in 9K's context), although some of the stuff such as making fields public might be seen as internals and thus subject to change. believe there's no reason not to merge.

**Pull request merged**
