### PR TITLE
Compatibility fixes for open3 on Windows

### LINKED ISSUE #6648: JRuby 9.2.17.0 fails to install sassc on Windows
On JRuby 9.2.16.0 it worked fine, so this sounds like a regression.

Reproduction:
```
gem install sassc -N
```

Expected and on 9.2.16.0: https://github.com/ruby/setup-ruby/runs/2212961109#step:20:9
```
Successfully installed ffi-1.15.0-java
Building native extensions. This could take a while...
Successfully installed sassc-2.4.0
2 gems installed
```

Actual on 9.2.17.0: https://github.com/ruby/setup-ruby/pull/165/checks?check_run_id=2227889407#step:20:10
```
Successfully installed ffi-1.15.0-java
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    current directory: D:/jruby-9.2.17.0/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
D:/jruby-9.2.17.0/bin/jruby.exe -I D:/jruby-9.2.17.0/lib/ruby/stdlib -r ./siteconf20210330-2584-1pgoh9i.rb extconf.rb
extconf failedNo such file or directory - {"SOURCE_DATE_EPOCH"=>"1617110021"}

Gem files will remain installed in D:/jruby-9.2.17.0/lib/ruby/gems/shared/gems/sassc-2.4.0 for inspection.
Results logged to D:/jruby-9.2.17.0/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/sassc-2.4.0/gem_make.out
Error: Process completed with exit code 1.
```

From https://github.com/ruby/setup-ruby/pull/165#issuecomment-810250236

Self-reminder: revert https://github.com/ruby/setup-ruby/commit/ad65390c0a7505ce47023b0555e762426132496b when this is fixed

### PR DESCRIPTION
**Pull request by headius**
This is a series of fixes to improve the behavior of the `open3` library when run on platforms where we cannot support native process launching (currently just Windows).

The bulk of changes here rewrite the non-native open3 shim to use java.lang.ProcessBuilder. Environment hash and options hash are also better supported.

### CODE REVIEW

**Comment by headius** [comment]
Note that the new `SyncOutputStreamChannel` is working around what I believe is a flaw in the default wrapper, detailed in an email to the OpenJDK core-libs-dev list here:

https://mail.openjdk.java.net/pipermail/core-libs-dev/2021-April/076025.html

**Comment by headius** [comment]
This now fixes #6648, tested on Windows 10 with msys/mingw64 tooling installed.

**Comment by ahorek** [comment]
I tested it also on 9.3 and you need to add ```require 'jruby'``` because ```JRuby.runtime``` doesn't work without it, but other than that it looks great.

thanks @headius

**Comment by headius** [comment]
@ahorek Great catch, thanks!

**Pull request merged**
