### PR TITLE
fiddle fixes

### PR DESCRIPTION
**Pull request by ahorek**
fixes https://github.com/jruby/jruby/issues/5956 and https://github.com/jruby/jruby/issues/5955

but this test case doesn't work yet
https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/test/mri/fiddle/test_func.rb#L73
I'm experimanting for now :)

### CODE REVIEW

**Comment by headius** [comment]
Nice! We definitely want to get Fiddle working better. Long term it might make more sense to do a direct implementation atop jnr-ffi, but for now getting the FFI version working is probably best.

**Comment by ahorek** [comment]
I splited two obvious errors to separate PRs
https://github.com/jruby/ruby/pull/2 https://github.com/jruby/ruby/pull/3

**Comment by ahorek** [comment]
one more interesting failure
https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/test/mri/fiddle/test_func.rb#L44

a string pointer #to_s should return a ruby string. That would be tricky to implement :)

**Comment by headius** [comment]
Do you think there's any work remaining here or could we go ahead with a merge?

**Comment by headius** [comment]
I have merged jruby/ruby#2 and jruby/ruby#3 across the two active branches `jruby-ruby_2_5_7` and `jruby-ruby_2_6_5` and incorporated their changes into the JRuby branches `master` and `ruby-2.6`.

I also figured out why the libc changes keeps disappearing: we were versioning `lib/ruby/stdlib/fiddle/jruby.rb` in both places when it's specific to JRuby, without any equivalent in CRuby, and subject to frequent updates. I modified all branches to reflect this, with messages about the proper versioning location added to jruby [here](https://github.com/jruby/jruby/commit/18082826ff06a10d71ec38c7648531210692790e) and [here](https://github.com/jruby/jruby/commit/b2b9e7d81c0e051d0c1ec919fb9f8946d9955c11).

(I see the spelling error now and will fix that).

I've also made sure that all changes from jruby/ruby's `jruby-ruby_2_5_7` and jruby/jruby's `master` branch have been incorporated back into the jruby/ruby `jruby-ruby_2_6_5` branch upon which the jruby/jruby `ruby-2.6` branch is based. See jruby/ruby@afa0b2506a928b6958163d74972ac6c94b2d9f7e.

We need a better way to manage our patch set against CRuby's stdlib.

**Comment by ahorek** [comment]
> Do you think there's any work remaining here or could we go ahead with a merge?

there're still many broken parts, but I think it's ready for review

**Comment by headius** [comment]
Everything here seems appropriate to me. I will merge and we can do other fixes in other PRs.

**Pull request merged**
