### PR TITLE
Add PowerPC64 little endian support in FFI

### PR DESCRIPTION
**Pull request by ghost**
Adds support for the ppc64le architecture in JRuby FFI.

### CODE REVIEW

**Comment by ayappanec** [comment]
Can this be fix be added to the jruby-1_7 branch? We are facing issues with Hbase shell which makes use of jruby-complete jar file. See HBASE-13338

**Comment by lbianc** [comment]
@ayappanec, see https://github.com/jruby/jruby/pull/2812.

**Comment by ayappanec** [comment]
Travis build fails when the task is "spec-compiler". I have no idea what this option does. Weird that it fails in jruby-1_7 branch.

**Comment by mkristian** [comment]
@ayappanec the PR was against master and the failing spec looked like something - unrelated.

merged the PR against jruby-1_7 - let's see what travis says to it ;)

**Comment by headius** [comment]
This was in 9k.pre1 and will be in 1.7.20, but I can only mark one milestone.

**Pull request merged**
