### PR TITLE
Fix Module.const_get for strings beginning with "::"

### PR DESCRIPTION
**Pull request by lumeet**
Yes, #1487 seems super easy.

### CODE REVIEW

**Comment by headius** [comment]
I'm not sure this is the right fix. For example, the following case should get the top-level Foo, and I don't think it will in your patch:

```ruby
Foo = 1
module Bar
end
Bar.const_get('::Foo')
```

**Comment by lumeet** [comment]
Hmm... am I missing something here?

test.rb:
```ruby
Foo = 1
module Bar
end
puts Bar.const_get('::Foo')

module A 
  class B 
  end 
end

put Object.const_get('::A::B')
```
Using MRI 2.2 and patched JRuby:
```shell
$ rbenv shell 2.2.0
$ ruby test.rb
1
A::B

$ bin/jruby test.rb
1
A::B
```

**Comment by headius** [comment]
Object.const_get('::A::B') is equivalent to Object.const_get('A::B'). Your other case does appear to show it working right, so perhaps I reviewed it poorly. Will try it locally.

**Comment by headius** [comment]
Ok, I have a case that better illustrates the problem:

```ruby
Foo = 1
module Bar; Foo = 2; end
Bar.const_get('::Foo')
```

Basically a leading :: should cause it to start searching at Object, rather than from the target class.

**Comment by lumeet** [comment]
Now this is a perfect example of sticking to test cases instead of thinking. I'll take a look at this again. :)

**Comment by headius** [comment]
@lumeet There are very likely test cases in MRI's suite (rake test:mri, test/mri/socket/**) or in RubySpec (rake test:ruby:fast, spec/ruby/core/socket/**) if you want to try getting them to run. If so, you can also remove tags/excludes from spec/tags or test/mri/excludes.

**Comment by headius** [comment]
BTW, you can get access to Object with `runtime.getObject`.

**Comment by headius** [comment]
Fixed via 5868779.

**Pull request closed without merging**
