### PR TITLE
Fix Float::INFINITY BigDecimal comparison

### LINKED ISSUE #4572: Can't compare BigDecimal with Float::INFINITY got FloatDomainError: NaN
JRuby version: `jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 +jit [darwin-x86_64]`
Output `uname`: `ruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 +jit [darwin-x86_64]`

I'm using JRuby on Rails. I can't compare `BigDecimal` with `Float::INFINITY`.
I can do this in **MRI**, but not in JRuby.
Ruby MRI version: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]`

```
# MRI

BigDecimal.new(100) <= Float::INFINITY
=> true

# JRuby
BigDecimal.new(100) <= Float::INFINITY
=> FloatDomainError: NaN
	from org/jruby/ext/bigdecimal/RubyBigDecimal.java:513:in `new'
	from org/jruby/ext/bigdecimal/RubyBigDecimal.java:638:in `new'
	from org/jruby/ext/bigdecimal/RubyBigDecimal.java:1163:in `<='
	from (irb):1:in `<eval>'
	from org/jruby/RubyKernel.java:1000:in `eval'
	from org/jruby/RubyKernel.java:1298:in `loop'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from /Users/opanmustopah/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/opanmustopah/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/opanmustopah/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/opanmustopah/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/opanmustopah/.rbenv/versions/jruby-9.1.7.0/lib/ruby/gems/shared/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<main>'
	from org/jruby/RubyKernel.java:961:in `require'
	from bin/rails:11:in `<main>'
```

I think this should work too on JRuby. 

Thanks in advance.

### PR DESCRIPTION
**Pull request by cammellos**
Hi, 

this fixes #4572 

Any feedback would be appreciated 

Thanks for the project!

andrea

### CODE REVIEW

**Comment by cammellos** [comment]
The build seems ok on my branch, https://travis-ci.org/cammellos/jruby . The test failing seems to be unrelated to the commit, shoud I take a look at it or is ok?

**Comment by kares** [comment]
@headius this seems to pass fine and isn't a big change, what do you think including the patch for 9.1 ?

**Comment by kares** [comment]
double checked that this wasn't the behaviour in MRI 2.3.1 but the specs seems to match MRI (>=) 2.3.3

**Comment by headius** [comment]
@kares Seems appropriate to include it in 9.1.11.

**Comment by headius** [comment]
Thanks for the fix and specs!

**Comment by eregon** [comment]
These specs do not pass on MRI 2.3.3 and 2.3.4:
```
for ruby in 2.3.3 2.3.4 2.4.0; do chruby $ruby; ruby -v -rbigdecimal -e 'p BigDecimal("-0.2E5556") > -Float::INFINITY'; done
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
false
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
false
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
true
```
It looks like a MRI bug in 2.3.x.

**Comment by eregon** [comment]
https://bugs.ruby-lang.org/issues/13674

**Pull request merged**
