### PR TITLE
Fix Module inclusion order

### PR DESCRIPTION
**Pull request by MSNexploder**
This fixes Module inclusion order as seen in #1938

### CODE REVIEW

**Comment by headius** [comment]
Failure appears to be directly related to the patch. Can you take a look into it?

**Comment by MSNexploder** [comment]
Will look into it. Looks like the whole Module thing is not as straightforward as I hoped. 😉

**Comment by MSNexploder** [comment]
Pretty sure I got the Module#prepend working again 🎉

**Comment by headius** [comment]
Well it passes tests...so I'll do a quick review and get it in! Thanks!

**Pull request merged**
