### PR TITLE
Fix UDPSocket#(send|write) to raise EMSGSIZE

### PR DESCRIPTION
**Pull request by etehtsea**

### CODE REVIEW

**Comment by kares** [comment]
one failure on spec:ruby:fast seems legit?
```
     [exec] 1)
     [exec] UDPSocket#write raises EMSGSIZE if msg is too long ERROR
     [exec] NoMethodError: undefined method `closed?' for nil:NilClass
     [exec] Did you mean?  clone
     [exec] /home/travis/build/jruby/jruby/spec/ruby/library/socket/udpsocket/write_spec.rb:18:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:1687:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1596:in `all?'
     [exec] org/jruby/RubyFixnum.java:299:in `times'
     [exec] org/jruby/RubyArray.java:1734:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/library/socket/udpsocket/write_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:979:in `load'
     [exec] org/jruby/RubyBasicObject.java:1687:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1734:in `each'
```

**Comment by etehtsea** [comment]
Nope, I'll look into it.

**Comment by etehtsea** [comment]
@kares fixed (I hope).

**Comment by kares** [comment]
:+1: looks good to me ... not sure if we're to merge PRs yet since the 9.1.9.0 release is fairly recent

**Comment by dwbutler** [comment]
If you're relying on the OS returning an error message of `Message too long`, you might have a bad time. It seems that Debian distributions return the error message `Message too large`. (See https://github.com/dwbutler/logstash-logger/issues/128)

**Comment by etehtsea** [comment]
@dwbutler according to [this comment](https://github.com/dwbutler/logstash-logger/issues/128#issuecomment-301279482) it look like Alpine specific issue.

Anyway it's possible to match both error messages.

**Pull request merged**
