### PR TITLE
[ffi] update to 1.15.1

### PR DESCRIPTION
**Pull request by ahorek**

### CODE REVIEW

**Comment by headius** [comment]
👍

**Comment by headius** [comment]
We probably should try to do this for 9.2 as well, yes?

**Comment by ahorek** [comment]
I don't think it's necessary and ffi wasn't gemified back in 9.2. So I would prefer to keep it for 9.3 unless there's some real issue that should be backported.

**Comment by headius** [comment]
Ah yes, I agree.

**Pull request merged**
