### PR TITLE
treat port nil as 0 for pack_sockaddr_in

### LINKED ISSUE #3156: Socket.pack_sockaddr_in fails for nil port (MRI doesn't)
JRuby raises a TypeError when the port is nil, whereas MRI treats nil the same way as zero.

```shell
> ruby-2.2.2 -rsocket -e 'p Socket.pack_sockaddr_in(nil, "127.0.0.1")'
"\x10\x02\x00\x00\x7F\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00"

> jruby-1.7.19 -rsocket -e 'p Socket.pack_sockaddr_in(nil, "127.0.0.1")'
TypeError: no implicit conversion from nil to integer
  pack_sockaddr_in at org/jruby/ext/socket/RubySocket.java:272
            (root) at -e:1
```

I'm using 1.7.19 in my example, but it seems the code in SocketUtils hasn't changed since 2012 in master, so I'm guessing it still applies to both 1.7.x and 9k. See https://github.com/jruby/jruby/blame/26d0b20ca324d082468bbcbc9d71709b142aa77b/core/src/main/java/org/jruby/ext/socket/SocketUtils.java#L131-L140

### PR DESCRIPTION
**Pull request by reuben-sutton**
Ensure compatability with MRI Ruby

closes #3156

### CODE REVIEW

**Comment by kares** [comment]
same here, please add the *spec/ruby/library/socket/shared/pack_sockaddr.rb* change in a separate commit

**Comment by kares** [comment]
... also maybe you could instead open a PR targeting **jruby-1_7** ... otherwise we have to cherry-pick

**Comment by reuben-sutton** [comment]
@kares not a problem - it's also an issue on master, so should I send two?

**Comment by reuben-sutton** [comment]
Hi @kares - That's done. It affected both 9k and 1.7 so I added #3225 to backport.

**Comment by kares** [comment]
great thanks, for the future if you only target 1_7 it will eventually end up in master as well with the merge
... for this one do not worry about it, thanks again.

**Pull request merged**
