### PR TITLE
Fix generated javadoc

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by enebo** [comment]
master will be 9.2.5.0 so we will not continue this branch for more than this  release

**Comment by pzygielo** [comment]
I see. 
Kinda hoped for micro-release of 9.2.4.1 :grin: 
Is the date for 9.2.5 known yet?

**Comment by enebo** [comment]
@pzygielo I am hoping this week...

**Comment by pzygielo** [comment]
Thank you for update. That's pretty good news!

**Pull request closed without merging**
