### PR TITLE
update jar-dependencies 0.4.2 reference in lib/pom.rb

### PR DESCRIPTION
**Pull request by ccutrer**
refs #7262

### CODE REVIEW

**Comment by headius** [comment]
We are so close!

The next problem is that the build itself uses JRuby, via a 9.3.0.0 version of jruby-complete.jar (see maven/jruby-jars/Mavenfile). This is run using the same installed gems as the currently-building JRuby, so it sees jar-dependencies 0.4.2, tries to activate it, but sees the same issue that prompted this whole issue. See the failing builds in this PR for the same old activation error.

I have merged this, since it gets things closer to green. The remaining work is figuring out how we can get the jruby-complete jar to work without seeing jar-dependencies 0.4.2.

**Comment by ccutrer** [comment]
I think we should yank jar-dependencies 0.4.2, and re-publish as 1.0.0. And ideally we could mark 1.0.0 as requiring jruby 9.3.7.0. That would allow other users to not "see" the changed version in most cases. But I don't know how to do that.  There's only the `required_ruby_version` directive, which is the CRuby version, and AFAICT is 2.6.8 for both jruby 9.3.6.0 and 9.3.7.0.

**Comment by headius** [comment]
@ccutrer Ok, I am concerned that this won't help because gems with dependencies on jar-dependencies do not have narrow-enough version descriptors. Going to poke around a bit to see if this is the case.

**Comment by ccutrer** [comment]
Yeah, I am too. That's why I was looking at the required_ruby_version, to give rubygems even more of an excuse to ignore the new version, I just don't know if we can change to 2.6.9 arbitrarily, since it seems like that's supposed to track CRuby.

**Comment by headius** [comment]
@ccutrer Yeah there's no easy way to tell RubyGems to require a specific version of JRuby because (I believe) the available required_ruby_version is only for the CRuby version or equivalent compatibility level in JRuby. We could perhaps bump our Ruby compat level but that isn't going to happen for the 9.3.7.0 which we hoped to put out this week.

In addition, with at least Psych having an open-ended jar-dependencies requirement, the upgraded gem is going to impact a lot of people on JRuby 9.3.6 and earlier. Even if we pinned a new release of Psych to 0.4.1, we'd still have lots of users out there with existing Gemfiles that suddenly break.

I'm going to yank the gem and revert the changes to our build and we'll take our time figuring out the most compatible way to do this update.

**Comment by ccutrer** [comment]
👍

**Pull request merged**
