### PR TITLE
normalize path (windows)

### LINKED ISSUE #3132: expandPathInternal Windows compatibility
MRI: File.realpath 'c:/test' => 'c:/test'
jRuby: File.realpath 'c:/test' => 'C:\ \test' (tested on 1.7.19 and 9.0.0.0 rc2)

It causes problems in Rails applications, because Rails.root path is invalid.

https://github.com/jruby/jruby/blob/da5dad6a960425375a2921c54fccd55971250076/core/src/main/java/org/jruby/RubyFile.java#L1592

### PR DESCRIPTION
**Pull request by ahorek**
fixes #3132

### CODE REVIEW

**Comment by kares** [comment]
@ahorek seems good but without a test is a little less worthy, any chance you do a test-case or tell us what use-case (sample .rb script) has been failing for you that the change fixes? thanks

**Comment by ahorek** [comment]
@kares - hi, most jruby tests don't work on windows and this is windows specific. Failing scenario is already described in the related issue.

spec/ruby/core/file/realpath_spec.rb
it "returns '/' when passed '/'" do
  File.realpath('/').should == '/'
end

=> for windows it should look something like this:
it "returns '/' when passed '/'" do
  if is_windows?
    File.realpath('/').should == 'C:/' # current behaviour 'C:\'
  else
    File.realpath('/').should == '/' # linux
  end
end

**Comment by kares** [comment]
seems good ... @mkristian what do you think of: `File.realpath('/').should == 'C:/' # NOT 'C:\'`

**Comment by mkristian** [comment]
the usual java vs. ruby paths. yes, this is OK. still a test which passes on windows as on unix would be great. one there we will have a CI running on windows and then it is important that we have a good test coverage for those windows only cases. test/jruby/test_file.rb is also a good place for such a test as this is in jruby direct control.

**Comment by kares** [comment]
@mkristian thanks I wasn't sure since its been a while when a tried JRuby on Windows. 
shall wait a while if @ahorek decides to add some cases at `test/jruby/test_file.rb` or merge as is.

**Comment by ahorek** [comment]
@kares - I've added very simple cases, is it ok? this fix should be also backported to JRuby 1.7.23

**Comment by kares** [comment]
@ahorek looks good, we're in the process of merging jruby-1_7 into master, 
... after we shall merge these and likely even back-port to jruby-1_7. thanks.

**Pull request merged**
