### PR TITLE
Update valid date range

### PR DESCRIPTION
**Pull request by edipofederle**

### CODE REVIEW

**Comment by headius** [comment]
Hmm I merged this before I noticed that no CI jobs ran. Could you throw another PR together for 9.3, since it has a full complement of GHA jobs?

**Comment by headius** [comment]
Or perhaps 9.3 was not affected?

**Comment by edipofederle** [comment]
> Or perhaps 9.3 was not affected?

checking

**Comment by edipofederle** [comment]
@headius 9.3 and 9.4 are affected by this as well.

**Pull request merged**
