### PR TITLE
Windows symlink

### LINKED ISSUE #3905: NotImplementedError: symlink unsupported or native support failed to load
I created an issue [here](https://github.com/jruby/warbler/issues/377) (sorry for the duplication, not sure where it should go). Trying to figure out a workaround, it seems as though it works in the 1.7 branch of JRuby, as well as 9.0.5.0, so perhaps a regression?

### Environment

Windows 10
JRuby 9.1.1.0 and 9.1.0.0

### Expected Behavior

```
λ gem install warbler -v 2.0.1
Successfully installed warbler-2.0.1
1 gem installed
```

### Actual Behavior

```
λ gem install warbler -v 2.0.1
NotImplementedError: symlink unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries

                  symlink at org/jruby/RubyFile.java:1035
  block in extract_tar_gz at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:386
                     each at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65
  block in extract_tar_gz at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:363
     block in open_tar_gz at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:457
                     wrap at org/jruby/ext/zlib/RubyGzipFile.java:94
              open_tar_gz at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:454
           extract_tar_gz at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:362
   block in extract_files at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:343
                     each at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65
   block in extract_files at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:340
                     open at org/jruby/RubyIO.java:1131
                     open at org/jruby/RubyKernel.java:305
             with_read_io at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package/file_source.rb:30
            extract_files at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/package.rb:337
            extract_files at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/installer.rb:766
                  install at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/installer.rb:296
                  install at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/resolver/specification.rb:97
         block in install at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/request_set.rb:166
                     each at org/jruby/RubyArray.java:1593
                  install at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/request_set.rb:156
              install_gem at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:205
    block in install_gems at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:255
                     each at org/jruby/RubyArray.java:1593
             install_gems at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:251
                  execute at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/commands/install_command.rb:158
   invoke_with_build_args at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/command.rb:310
             process_args at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/command_manager.rb:169
                      run at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/command_manager.rb:139
                      run at C:/tools/jruby/9.1.1.0/lib/ruby/stdlib/rubygems/gem_runner.rb:55
                    <top> at C:/tools/jruby/9.1.1.0/bin/jgem:21
                     load at org/jruby/RubyKernel.java:962
                    <top> at C:/tools/jruby/9.1.1.0/bin/gem:4

```

### 1.7.25
```
λ jruby --version
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_92-b14 +jit [Windows 10-amd64]

λ gem install warbler -v 2.0.0
Fetching: warbler-2.0.0.gem (100%)
Successfully installed warbler-2.0.0
1 gem installed

λ gem install warbler -v 2.0.1
Successfully installed warbler-2.0.1
1 gem installed
```

### 9.0.5.0
```
λ jruby --version
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [Windows 10-amd64]

λ gem install warbler -v 2.0.0
Fetching: jruby-jars-9.1.1.0.gem (100%)
Successfully installed jruby-jars-9.1.1.0
WARNING: SSLSocket#session= is not supported
Fetching: jruby-rack-1.1.20.gem (100%)
Successfully installed jruby-rack-1.1.20
Fetching: rubyzip-1.2.0.gem (100%)
Successfully installed rubyzip-1.2.0
Fetching: warbler-2.0.0.gem (100%)
Successfully installed warbler-2.0.0
4 gems installed

λ gem install warbler -v 2.0.1
Fetching: warbler-2.0.1.gem (100%)
Successfully installed warbler-2.0.1
1 gem installed
```

Fails in both 9.1.1.0 and 9.1.0.0 with the same stack trace

### PR DESCRIPTION
**Pull request by headius**
This incorporates symlink support from @djberg96's win32-file and ffi-win32-extensions projects.

@djberg96 Ideally we'd just include this in JRuby under our tri-license (EPL, GPL2, LGPL2). If that's ok with you, let us know you consent to your code being licensed that way.

This seems to be everything I need, but when I try to install warbler (this is intended to fix #3905) I get this peculiar error:

```
λ gem install warbler
ERROR:  While executing gem ... (SystemCallError)
    Unknown error 1314 - CreateSymbolicLink
```

So this isn't quite ready yet.

### CODE REVIEW

**Comment by headius** [comment]
Ahh, seems like this may be a permission issue on Windows 7: http://stackoverflow.com/questions/26020777/createsymboliclink-runs-on-windows-8-returns-error-code-1314-on-windows-7

Maybe it's time for me to update my Windows to 10, but I think you want this to work on Windows 7 too, right @djberg96?

**Comment by djberg96** [comment]
@headius Yeah, we don't try to elevate privileges, users would have to install with administrator rights.

I'm not sure if we want to do that, but you certainly could. And you definitely have permission to copy/paste whatever you need.

I still don't understand this rake version error, though.

**Comment by headius** [comment]
Yeah I'm not sure about that error either. I'll see if I can reproduce it.

**Comment by headius** [comment]
Will merge after we have a clean travis run.

**Comment by headius** [comment]
Rebase to master will be clean, so I'm merging now.

**Pull request merged**
