### PR TITLE
Add support for named captures in StringScanner (fixes #1067)

### LINKED ISSUE #1067: [2.1] StringScanner named captures
https://bugs.ruby-lang.org/issues/8343

Also perhaps https://bugs.ruby-lang.org/issues/836

### PR DESCRIPTION
**Pull request by MSNexploder**
#test_AREF should pass but fails locally with "undefined method `assert_raise_with_message'" and i'm not sure why. :sweat:

### CODE REVIEW

**Comment by MSNexploder** [comment]
Actually this is my very first pull request for JRuby so...

no idea

**Comment by enebo** [comment]
@MSNexploder ah yeah assert error is because you need to run with test/mri/runner.rb:

```text
/Users/enebo/work/jruby/bin/jruby -X-C -r ./test/mri_test_env.rb test/mri/runner.rb  -q -- ruby/test_alias.rb
```

**Comment by enebo** [comment]
@MSNexploder Sorry we left this so long...can you rebase this it no longer applies cleanly...

**Comment by MSNexploder** [comment]
Actually this pull request is no longer needed. @headius already fixed this in 2d6b3f6.

**Comment by enebo** [comment]
@MSNexploder great.

**Pull request closed without merging**
