### PR TITLE
Fix issues with File.dirname

### LINKED ISSUE #4116: File.dirname interprets backslashes as path separators on Mac OS X
### Environment

```
~/> ruby -v
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [darwin-x86_64]
~> uname -a
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```
### Expected Behavior

```
~> ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin15.6.0]
~> irb
irb(main):001:0> path = 'this/path/has/filename\that\contains\backslashes'
=> "this/path/has/filename\\that\\contains\\backslashes"
irb(main):002:0> File.dirname path
=> "this/path/has"
irb(main):003:0>
```

```
~> ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
~> irb
irb(main):001:0> path = 'this/path/has/filename\that\contains\backslashes'
=> "this/path/has/filename\\that\\contains\\backslashes"
irb(main):002:0> File.dirname path
=> "this/path/has"
irb(main):003:0>
```
### Actual Behavior

```
~> ruby -v
jruby 1.7.21 (1.9.3p551) 2015-07-07 a741a82 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [darwin-x86_64]
~> irb
irb(main):001:0> path = 'this/path/has/filename\that\contains\backslashes'
=> "this/path/has/filename\\that\\contains\\backslashes"
irb(main):002:0> File.dirname path
=> "this/path/has/filename\\that\\contains"
irb(main):003:0>
```

```
~> ruby -v
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.31-b07 on 1.8.0_31-b13 +jit [darwin-x86_64]
~> irb
irb(main):001:0>  path = 'this/path/has/filename\that\contains\backslashes'
=> "this/path/has/filename\\that\\contains\\backslashes"
irb(main):002:0>  File.dirname path
=> "this/path/has/filename\\that\\contains"
irb(main):003:0>
```
### Additional Information

The code in [RubyFile.java](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyFile.java) uses hard-coded path separator values, e.g. line 724 `if (endChar == '/' || endChar == '\\') {`, rather than system dependent constants, such as Java `File.separator`.

### PR DESCRIPTION
**Pull request by jellymann**
This fixes #4116

e.g. The result of `File.dirname('/foo/bar\baz')` on Windows is `"/foo/bar"`
while on Unix it is `"/foo"`, since `"bar\baz"` is a single file name (`\` is not a path separator in Unix)

As an added bonus, this also fixes a number of inconsistencies with MRI with regard to Windows UNC paths, notably:
1. A typical UNC path is made up of `"//<host>/<share>/path/to/file.ext"`, where the "root" is `"//<host>/<share>"`
   
   This means that, while `File.dirname('//foo/bar/baz')` is `"//foo/bar"`, `File.dirname('//foo/bar')` is still `"//foo/bar"` (since `"//foo/bar"` is the "root").
2. Extraneous "leading" separators are removed, e.g. `File.dirname('////foo/bar/baz')` is `"//foo/bar"`
3. This logic must not be confused with Unix paths, where there should be no more than 1 separator at the beginning of the string.
   
   e.g. `File.dirname('/foo/bar')` should still be `"/foo"`, on both Unix and Windows.
4. For all of the above, `/` and `\` are completely interchangeable at all times on Windows.
5. Windows UNC paths are not recognised at all on Unix, e.g. `File.dirname('//foo/bar')` is still `"/foo"`.

### CODE REVIEW

**Comment by jellymann** [comment]
@enebo I've had a look at the spec. Is there any reason why it specifically dictates that `File.split` deviates from MRI?

If `File.split` is to be "fixed" (i.e. made to pass current spec), it will no longer be consistent with `File.dirname`, which is not following POLA.

If `File.split` _must_ pass the current spec, _and_ we wish to remain consistent with `File.dirname`, then the deviation should be added to `File.dirname`. However, #4116 will not be resolved.

Removing the deviation from the `File.split` spec is, in my opinion, the most "correct" way to resolve the issue. However, this may be considered a breaking change, and it would depend heavily on the reason for the deviation in the first place.

Looking at the spec, it seems this deviation has been in there as early as 2008, perhaps even earlier...

**Comment by enebo** [comment]
@jellymann ok that is interesting.  I have seen bad specs.  If so we can tag it out in our tags file with Windows: (vs Fail: or Error:) then it will skip testing that spec on windows.  I guess ultimately ruby/spec should get fixed then.

**Comment by headius** [comment]
We (or you) can fix the spec directly in our repo; @eregon periodically merges those changes across.

**Comment by jellymann** [comment]
@headius @enebo I took out the deviation in File.spec, and it is now failing because File.basename is also not taking system-specific path separators into account (it does the same as File.dirname did, just replacing all `\` with `/` before processing)

I will investigate MRI's behaviour and write tests for basename, and then fix the implementation.

**Comment by jellymann** [comment]
@headius @enebo I've fixed basename (and consequently File.split as well) so that it behaves consistently with MRI.

Sorry it took a while, I had a family crisis and was out of town for a bit.

**Comment by enebo** [comment]
@jellymann sorry I did not merge this a long time ago.  We shall see how it works.  At the time you submitted this our CI was pretty messed up so I might ping you if something else breaks as part of fallout.

**Pull request merged**
