### PR TITLE
#4752 Start adding JMH benchmarks

### PR DESCRIPTION
**Pull request by original-brownbear**
First step towards JMH benchmarks as discussed in #4752 

* Added basic JMH bootstrap
* Ported `BenchArrayCopy`  to JMH

The output looks like this:

```sh
# Run complete. Total time: 00:01:32

Benchmark                             Mode  Cnt          Score         Error   Units
ArrayCopyBenchmark.benchSystemCopy0  thrpt   10         54.219 ±       2.056  ops/ns
ArrayCopyBenchmark.benchSystemCopy1  thrpt   10          0.338 ±       0.005  ops/ns
ArrayCopyBenchmark.benchSystemCopy2  thrpt   10          0.326 ±       0.010  ops/ns
ArrayCopyBenchmark.benchSystemCopy3  thrpt   10          0.308 ±       0.005  ops/ns
ArrayCopyBenchmark.benchSystemCopy4  thrpt   10          0.295 ±       0.009  ops/ns
ArrayCopyBenchmark.benchSystemCopy5  thrpt   10          0.205 ±       0.009  ops/ns
ArrayCopyBenchmark.benchUtilsCopy0   thrpt   10  341532540.079 ± 9535315.085  ops/ns
ArrayCopyBenchmark.benchUtilsCopy1   thrpt   10          3.179 ±       0.110  ops/ns
ArrayCopyBenchmark.benchUtilsCopy2   thrpt   10          0.854 ±       0.015  ops/ns
ArrayCopyBenchmark.benchUtilsCopy3   thrpt   10          0.532 ±       0.055  ops/ns
ArrayCopyBenchmark.benchUtilsCopy4   thrpt   10          0.288 ±       0.013  ops/ns
```

Usage would be:

```sh
$ cd bench 
$ mvn clean install
$ java -jar target/jruby-benchmark.jar
```

### CODE REVIEW

**Comment by original-brownbear** [comment]
@kares there we go for step 1, let me know what you think if you have a sec :)

**Comment by kares** [comment]
very najs, am all for it!

**Comment by kares** [comment]
can already find a use-case for this piece of code, thanks @original-brownbear

**Comment by original-brownbear** [comment]
@kares np :)

**Pull request merged**
