### PR TITLE
[#2867] modified Date#>> to take calendar reforms under consideration

### PR DESCRIPTION
**Pull request by raeoks**
- added tests for next month with calendar reform
- uses solution provided in #1769 comments
- also fixes issues #1769

### CODE REVIEW

**Comment by kares** [comment]
@raeoks would you mind trying to target **jruby-1_7** so that this is fixed in JRuby 1.7.x as well?

@eregon since its mostly your work-around ... any thoughts on getting those in?

**Comment by eregon** [comment]
These tests would be useful in RubySpec. You can just do a separate commit touching `spec/ruby`.

Well, if this behavior must be supported, I'd say there is not much choice.

**Comment by raeoks** [comment]
I'll move test cases from `test/mri/date/test_date_arith.rb` to `spec/ruby/library/date`'s `add_month_spec.rb` and `next_year_spec.rb` files.
Also I'll be start working on creating a new pull request to fix same issue on jruby-1_7.

**Comment by headius** [comment]
The changes look ok to me but I defer to @eregon on when and whether this should merge.

**Comment by eregon** [comment]
@raeoks Could you move the test cases to specs? Or should I do it?

**Comment by raeoks** [comment]
@eregon I'll do and doing it right now.

**Comment by raeoks** [comment]
@eregon Should I create a new pull request resolving #2867 for Jruby 1.7?

**Comment by eregon** [comment]
I guess yes but better ask @kares.
@raeoks Is this PR ready to be merged?

**Comment by kares** [comment]
optimally, there would be only one PR targeting **jruby-1_7** (branch is periodically merged to master) ...

**Comment by eregon** [comment]
I applied the commits to 1.7, 1.9-mode (1.8 Date is just so different and should not be affected the same way by this bug): 40e9140209d944f424c965ccdf8b2304b8c2aade and ec80a3209e54cb259c45851375d0a2c2fb7334d0.

I guess the merge in this case would not work so well (date.rb moved quite a bit), so I'd rather merge #3157 in master instead.

**Pull request closed without merging**
