### PR TITLE
update jffi and release version for JRuby 1.7

### PR DESCRIPTION
**Pull request by DJRickyB**
prevents SEGFAULTs described in https://github.com/jruby/jruby/issues/4506

I understand the intent is not to update 1.7 anymore, but this change is being tested at our organization currently and could save us a lot of grief

### CODE REVIEW

**Comment by headius** [comment]
Sorry for the delay in looking at this. Unfortunately we do not have plans or resources to do a 1.7.28 release. I'll ping @enebo here and we can discuss a path forward. Is there no way for you to update to a JRuby 9.x version?

**Comment by headius** [comment]
Oops, I marked this for 9.1.17 without realizing 9.1 has already been bumped up to jffi 1.2.16.

**Comment by DJRickyB** [comment]
Actually we were still getting segfaults even after this patch.  I see the initial issue has some recent activity.  We are going to be pushing our devs to convert legacy projects to 9k for sure

**Comment by headius** [comment]
@DJRickyB Yes, in #4506 there's discussion about how to fix this better in jnr-ffi, but so far no patch from the contributor. It would likely require a rebuild of the native bits of jffi, which means there's a bit of a long tail in getting it released (we support some obscure platforms that would need rebuilds). But there's a solution out there.

Can you describe your application and how you're running it? There are some workarounds that may help.

**Comment by DJRickyB** [comment]
we have multiple rails apps co-existing on tomcat using (now) a patched version of JRuby 1.7 with the change in this PR.  Each is in a separate warbler-generated war running via jruby-rack.

  Sporadic segfaults have been traced back to JFFI and match #4506

**Pull request closed without merging**
