### PR TITLE
Fix warn specs (sans rubygems needing PR)

### PR DESCRIPTION
**Pull request by enebo**
Various specs now passing.  Rubygems has a core_ext on Warning#warn which will never pass kw on JRuby.  I plan on making a PR for that soon.

### CODE REVIEW

**Comment by headius** [comment]
Are the spec:ruby:fast failures expected?

**Comment by enebo** [comment]
@headius yes.  This works if we change rubygems core_ext of Kernel#warn.  A PR is still needed there.  I am keepign this open until I make something.

**Comment by enebo** [comment]
https://github.com/rubygems/rubygems/pull/6002 is the pull request which needs to be merged and released for us to land this PR.

**Comment by deivid-rodriguez** [comment]
RubyGems 3.3.25 is out 👍.

**Comment by headius** [comment]
I updated RG and Bundler in 6d81f8308b so this can be merged.

**Pull request merged**
