### PR TITLE
Test passing control between two threads in the ConditionVariable spec

### PR DESCRIPTION
**Pull request by asppsa**
This tests (J)Ruby's ability to safely switch back and forth between two threads that both have locks on a single mutex, as identified in #5863.

I'm happy to make changes to this spec if needed.  In particular, I wasn't sure what a suitable timeout should be (went with 5 seconds), and also whether to add this to the spec for `#signal` or `#wait`.  I went with `#signal` because it seems that the failure is in the ability to wake up after going to sleep.

### CODE REVIEW

**Comment by asppsa** [comment]
Also, I should note that I used MRI 2.6 to check that this spec can pass.

**Comment by asppsa** [comment]
@headius, I'll rebase this onto master to see if it passes now.

**Comment by headius** [comment]
Excellent, thank you! Assuming this goes green I'll merge it in.

**Comment by headius** [comment]
Two suites failed despite my best efforts, but I'm convinced they're just caching problems with the jnr-constants maven artifact. Merging this in...thank you for your thoroughness @asppsa!

**Comment by eregon** [comment]
@asppsa Thanks for this good spec, it also caught a bug in TruffleRuby!

**Pull request merged**
