### PR TITLE
sequester tmp directories

### PR DESCRIPTION
**Pull request by tduehr**
Moves tmp_\* directories under tmp/.

### CODE REVIEW

**Comment by nirvdrum** [comment]
Has there been any decision on this one?

**Comment by headius** [comment]
I still don't like the idea of having `tmp` committed to the repository with nothing but `.gitignore` in it. We should just fix the test to use a system-level temp location. That would be good enough, right?

**Comment by tduehr** [comment]
I agree that would be better.

**Comment by headius** [comment]
There was an additional problem with the test: it used `rm_f` instead of `rm_rf` to delete the `@tmpdir` in teardown. In other words, it didn't actually delete it. Both issues are fixed now.

**Pull request closed without merging**
