### PR TITLE
Remove running threads on tearDown

### PR DESCRIPTION
**Pull request by stewartmatheson**
See #3313 .

### CODE REVIEW

**Comment by rtyler** [comment]
This looks reasonable to me, but what do I know :)

**Comment by headius** [comment]
Oh, is this sufficient for #3313? I thought you would have expected JRuby to actually *kill* those threads, which I wasn't willing to do (and might not even be able to do, safely).

**Comment by stewartmatheson** [comment]
Hey Charles,

Thanks for the response. I'm not %100 sure how to would "kill" threads. My test indicates that the threads are no longer running after calling tearDown so I was assuming that the patch was killing threads. Is there a better way to do this?

As for safely my thoughts are that tearDown was the same as killing a ruby process.  Developers working with MRI seem to be starting threads with no intent of stopping them safely. Mongo's new ruby driver is an example of this, they start a heartbeat thread that never dies.

**Comment by headius** [comment]
@stewartmatheson It's possible to iterate over all threads and kill them now, using Ruby.getThreadService().getActiveRubyThreads(). Note that this will usually only give you the threads initiated from within that JRuby instance, but I think that's what you want.

For the record, I do not believe our Ruby.teardown should forcibly kill off user threads. We've actually had complains that teardown does *too much* in cases where people just allow the main thread to terminate but *expect* their other threads to keep running. We can't please everyone here.

However, I think for embedding purposes it's worth adding a *new* mechanism to "teardown and stop threads". This *might* be the default behavior for ScriptingContainer, but that's debatable.

Probably not going to get this until major work in 9.2. Help wanted!

**Comment by headius** [comment]
I have created an updated version of this in #5390 that clears a few additional references, but it still does not do anything to kill threads. I am starting to suspect that's not a necessary condition to fix #3313?

**Pull request closed without merging**
