### PR TITLE
Update JNR projects to latest

### PR DESCRIPTION
**Pull request by headius**
This picks up changes to the automatic module name from
jnr/jffi#67 but also updates JNR projects across the board to grab
all recent bug fixes.

### CODE REVIEW

**Comment by headius** [comment]
@enebo This is a larger change than the master update in #6481 but I think it should go into 9.2.14 to pick up various fixes to the JNR projects that have only been applied to master so far.

**Comment by ahorek** [comment]
https://github.com/jruby/jruby/pull/6460 should be backported with this change

**Comment by headius** [comment]
> #6460 should be backported with this change

Good call, I can take care of it.

**Comment by headius** [comment]
@ahorek This PR appears to be hanging in a multicast socket test. Maybe you remember another fix we did on master that needs to be backported?

**Comment by headius** [comment]
Aha... perhaps the constant fixes here: https://github.com/jruby/jruby/pull/6388

**Comment by headius** [comment]
The fixes in #6388 do not appear to address the hanging test.

**Comment by headius** [comment]
Ok possibly false negative since this test appears to hang on macOS even on master. I have pushed cherry-picks of all the changes that seemed relevant.

**Comment by headius** [comment]
This is ready to merge, @enebo. The hangs were apparently related to the updated socket constants that @ahorek and I applied to master; when jnr-constants was updated those same changes needed to be applied to the 9.2 branch. The risk here seems fairly low but I would like a review before merging.

**Comment by ahorek** [comment]
could you release https://github.com/jnr/jnr-constants/commits/master ? it should be safe.

I think that's all. +1

**Comment by headius** [comment]
@ahorek Ahh it has been a while for that one. I will release it and the projects that use it.

**Pull request merged**
