### PR TITLE
[Truffle] Adding initial MRI test index and excludes.

### PR DESCRIPTION
**Pull request by bjfish**

### CODE REVIEW

**Comment by eregon** [comment]
Did you use a script to generate the excludes?

**Comment by chrisseaton** [comment]
Didn't you still need #2826 to run these?

**Comment by bjfish** [comment]
@chrisseaton  Yes, it needs this to run test/unit unmodified https://github.com/jruby/jruby/issues/2826 and also these: https://github.com/jruby/jruby/issues/2836,  https://github.com/jruby/jruby/issues/2825, https://github.com/jruby/jruby/issues/2838.

**Comment by bjfish** [comment]
@eregon Yes, I ran all the tests like this `jt test mri ruby/test_alias || jt test mri ruby/test_clone.rb || ... `. Then, I used this script to generate the test index and exclude files and directories: https://gist.github.com/bjfish/e6965cb3ae9226d83998

I hope to extract some of that logic later on to create a tag/untag tool for these tests.

**Comment by bjfish** [comment]
@chrisseaton Also, this byteslice PR is need for the tests to complete successfully: https://github.com/jruby/jruby/pull/2848/files

**Comment by bjfish** [comment]
@eregon fixed the excludes for test classes inside of modules here: https://github.com/jruby/jruby/issues/2849. So, I've uncommented all these modules tests in the test index to add them back

```
Finished tests in 36.891000s, 45.1872 tests/s, 3343.3900 assertions/s.

1667 tests, 123341 assertions, 0 failures, 0 errors, 11 skips
```.

**Pull request merged**
