### PR TITLE
backport: fnmatch not matching glob syntax

### PR DESCRIPTION
**Pull request by ahorek**
backport https://github.com/jruby/jruby/issues/7942 to 9.3.x

### CODE REVIEW

**Comment by shivanesabharwal** [comment]
@headius Is there a timeline for when new patch release builds make it into Maven Central repository?

**Comment by headius** [comment]
@shivanesabharwal No not really. If there's significant community need we will run a release. We would recommend upgrading to 9.4 if you are stuck on a 9.3 issue.

**Comment by shivanesabharwal** [comment]
@headius unfortunately, we are running into issues upgrading the minor version in our build and would appreciate a patch release for 9.3 branch if possible. Is that feasible?

**Comment by headius** [comment]
@shivanesabharwal We would like to help resolve any issues preventing you from upgrading to 9.4, but I will chat with @enebo to see when we can get a 9.3 update released.

**Pull request merged**
