### PR TITLE
[Truffle] Add copy of 2.2.2 stdlib

### PR DESCRIPTION
**Pull request by pitr-ch**
JRuby+Truffle does not support 2.3 features yet, so it needs copy of 2.2.2 stdlib.
cc @jruby/truffle, @headius, @enebo

### CODE REVIEW

**Comment by headius** [comment]
Ugh...we really don't want to have two copies of stdlib in the repo again if we can avoid it. Perhaps the few features you need to use the 2.3 stdlib would not be too difficult to implement?

**Comment by chrisseaton** [comment]
Yeah we thought you may not be keen - it's a reasonable response.

Ideally we'll implement the 2.3 features quickly, but in the mean time it's not great to be working on other things and having some random failures here and there from the new stdlib.

How long could we have this in? Are you releasing imminently?

**Comment by pitr-ch** [comment]
The copy was updated to contain only what's actually needed by JRuby+Truffle, it has only 3,4MB now.

**Comment by enebo** [comment]
I also find this undesirable but so long as the timeframe does not stretch multiple point releases and there is a plan for removing this I think we can eat the extra space in a single point release.  I partially blame us for not collaborating on this version move a bit more.

**Comment by pitr-ch** [comment]
Ok thanks, it helps a lot. I'll rebase and merge.

**Comment by kares** [comment]
you guys considered how confusing such a release might get for end users - even ones trying out truffle?

**Comment by pitr-ch** [comment]
@kares valid point, I'll move the copy to truffle directory so it's clear what is the purpose of the copy.

**Pull request merged**
