### PR TITLE
[fix] Enumerable#any? does not require an arg

### LINKED ISSUE #5968: Enumerator#any? is wrong for sequence of empty arrays
### Environment

```console
$ cat jruby_bug.rb 
p [[]].any?
p [[]].to_enum.any?
```

### Expected Behavior

```console
$ ruby -v                      
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 11.0.5-ea+10-post-Ubuntu-0ubuntu1 on 11.0.5-ea+10-post-Ubuntu-0ubuntu1 +jit [linux-x86_64]
$ ruby jruby_bug.rb 2>/dev/null
true
true
```
(same for MRI)

### Actual Behavior

```console
$ ruby -v                      
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 11.0.5-ea+10-post-Ubuntu-0ubuntu1 on 11.0.5-ea+10-post-Ubuntu-0ubuntu1 +jit [linux-x86_64]
$ ruby jruby_bug.rb 2>/dev/null
true
false
```

Discovered through https://github.com/rubocop-hq/rubocop/pull/7489

### PR DESCRIPTION
**Pull request by ahorek**
fixes #5968

### CODE REVIEW

**Comment by enebo** [comment]
@ahorek Thanks for the fast fix!  contribution on this to ruby/spec would also be helpful

**Comment by kares** [comment]
since this seems like a regression we might have wanted to target the *jruby-9.2* branch
(just in case if there's another 9.2 release)

**Comment by enebo** [comment]
@kares I am hoping not but I will cherry pick it there.

**Comment by headius** [comment]
Looks like this never got cherry-picked. I'll take care of it.

**Comment by headius** [comment]
Retargeted to 9.2.12 and cherry picked into #6285.

**Pull request merged**
