### PR TITLE
CI: quick test on how ARM64 is doing

### PR DESCRIPTION
**Pull request by kares**
... (sorry I do not have credits to test on my own fork :crying_cat_face: )

### CODE REVIEW

**Comment by headius** [comment]
Linux AArch64 should be pretty good but I have not made an effort to tag off things that do fail there. Apple Arm64 still has issues.

**Comment by kares** [comment]
for whatever reason CI stopped working recently - now only runs AppVeyor but not Travis nor GH actions :crying_cat_face:

**Comment by headius** [comment]
It's not because it is a draft is it?

**Comment by kares** [comment]
moved to https://github.com/jruby/jruby/pull/6567

**Pull request closed without merging**
