### PR TITLE
UNIXSocket#recv_io, UNIXSocket#send_io implementation using JNR

### PR DESCRIPTION
**Pull request by mrbrdo**
`recv_io_spec.rb` and `send_io_spec.rb` seem to now be passing. Also did a check with a script and seems to be working properly. Thorough review would be welcome, as this is my first JRuby PR.

Based on MRI code https://github.com/ruby/ruby/blob/trunk/ext/socket/unixsocket.c#L206
And on the test from `jnr-posix`: https://github.com/jnr/jnr-posix/blob/master/src/test/java/jnr/posix/IOTest.java#L163

I did skip this part: https://github.com/ruby/ruby/blob/af68619a6c0de0d4f08d092d65143abcf2cedce3/ext/socket/unixsocket.c#L355 (L355-L404)
I'm not sure if this is even relevant to JRuby nor do I completely understand what it is doing.

Cheers

### CODE REVIEW

**Comment by mrbrdo** [comment]
@headius do you need something else before this and #3494 can be merged?

**Comment by mrbrdo** [comment]
@headius @kares ping

**Comment by mrbrdo** [comment]
@headius @kares reping

**Comment by kares** [comment]
sorry I can not decide whether its correct without any tests, try [rebasing off a green build](https://github.com/jruby/jruby/commit/8a0486125512255f663bc5105ffa9009e9562de8) and [un-exclude](https://github.com/jruby/jruby/blob/master/test/mri/excludes/TestSocket_UNIXSocket.rb) some of the [MRI tests](https://github.com/jruby/jruby/blob/master/test/mri/socket/test_unix.rb) or add new ones

**Comment by mrbrdo** [comment]
@kares @headius the MRI tests are checking `IO#close_on_exec?` which is not implemented on JRuby, so I cannot get those tests passing in their current form. Please advise?

**Comment by mrbrdo** [comment]
Also the failure in the tests above can't be my fault...

**Comment by headius** [comment]
Sorry for the delay on this, @mrbrdo...travel and holidays tied me up I guess. We'll get this merged right away.

**Comment by mrbrdo** [comment]
Thanks @headius , don't forget about #3494 :)

**Pull request merged**
