### PR TITLE
[etc] implement #confstr and #pathconf

### PR DESCRIPTION
**Pull request by ahorek**
depends on https://github.com/jnr/jnr-posix/pull/154

### CODE REVIEW

**Comment by headius** [comment]
@ahorek We should either get an impl in place or close this, I think...

**Comment by ahorek** [comment]
@headius let's implement it!

could you review https://github.com/jnr/jnr-posix/pull/154 ? Thanks

**Comment by headius** [comment]
@ahorek I reviewed and merged jnr/jnr-posix#154 and can do a release any time. For now I've deployed a snapshot build of 3.1.1 which can be used to test this PR (we should release and use 3.1.1 non-snapshot before merging).

**Comment by headius** [comment]
Use `3.1.1-SNAPSHOT` as the version in JRuby to test.

**Comment by headius** [comment]
Oops, my mistake... 3.1.1 already went out, so it's 3.1.2-SNAPSHOT.

**Comment by ahorek** [comment]
ok, there's one small fix on Windows https://github.com/jnr/jnr-posix/pull/155

this should be ready for review. Thanks @headius

**Comment by headius** [comment]
I merged jnr/jnr-posix#155 and pushed a new snapshot. Will give it a few minutes and then restart CI to pick up the change.

**Comment by headius** [comment]
Looks good to me, I will push a jnr-posix release and we can update and merge.

**Comment by headius** [comment]
I released jnr-posix and went ahead and updated master to use it. You can update the PR to the released version and once this goes green we'll merge it!

**Comment by headius** [comment]
I forgot I can make the change too. 🤪

**Review by headius — APPROVED** [review]

**Comment by headius** [comment]
All good, thanks!

**Pull request merged**
