### PR TITLE
Remove not used methods

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by kares** [comment]
`RubyInstanceConfig` is sensitive API, it might need to stay and go `@Deprecated` instead, right @enebo ?

**Comment by enebo** [comment]
@kares @yui-knk yeah this one I don't think we should remove or annotate as a deprecation.  In this case, an extension author might want to know if ruby is from a command line.  We don't want them to be calling __FILE__ for this.  These decisions are a little difficult YAGNI OTOH it is reasonable information in a consistent location someone might actually use?

The larger issue is we do not have an explicit native extension API (beyond ScriptingContainer which arguably is more of an embedding API) so I could see extension authors expecting this class to remain unchanged.

**Comment by yui-knk** [comment]
@enebo 
Sorry, I didn't explain it clearly enough.
`RubyInstanceConfig` has `public boolean hasInlineScript()` and `public boolean isInlineScript()`. Both of them return `hasInlineScript `, so I think we can omit (or deprecate) one of them.

**Comment by enebo** [comment]
@yui-knk oh ok yeah I agree then one could be deprecated.  My logic would be to keep hasInlineScript() since it implies it was invoked as inline script but it may loads lots of other Ruby.  Anyone else have an opinion?

**Pull request closed without merging**
