### PR TITLE
Update to ruby/spec@517f06f

### PR DESCRIPTION
**Pull request by andrykonchin**

### CODE REVIEW

**Comment by headius** [comment]
Thanks @andrykonchin!

Going forward, I think we should either add you as a committer (so you can merge these) or we should take over the update ourselves. Thoughts?

**Comment by andrykonchin** [comment]
Yeah, it would be great if I could merge such PRs on my own.

**Comment by headius** [comment]
@andrykonchin I have sent an invite to add you to a writable team!

**Comment by andrykonchin** [comment]
Thank you!

**Pull request merged**
