### PR TITLE
fix resolv on windows

### PR DESCRIPTION
**Pull request by ahorek**
bug #4755

### CODE REVIEW

**Comment by kares** [comment]
`sun.net.dns.ResolverConfiguration` is OpenJDK specific right? and it will get hidden away under Java 9+
definitely better than nothing I am just asking if you have any input or ideas on doing this in a different way.

**Comment by ahorek** [comment]
sun.net.dns.ResolverConfiguration is marked as depricated, but it still works
jruby 9.2.0.0-SNAPSHOT (2.5.0) 2018-05-10 00c19bb Java HotSpot(TM) 64-Bit Server VM 10.0.1+10 on 10.0.1+10 +jit [mswin32-x86_64]
btw. with this patch the behaviour is the same as 9.1.17.0

I think the only way to do this right and fix https://bugs.ruby-lang.org/issues/12604 is to reimplement this
https://github.com/ruby/ruby/blob/202bbda2bf5f25343e286099140fb9282880ecba/ext/win32/resolv/resolv.c using JNI.

What do you think? Should I try it or is there a better way?

**Comment by headius** [comment]
@ahorek Is this fix perhaps "good enough" to merge now in case we can't do the "right" fix before the 9.2 release (within a week from now)?

**Comment by ahorek** [comment]
my only concern is that sun.net.dns.ResolverConfiguration will become deprecated (I tested it on Oracle's Java 8 and Java 10 and it works fine for now)
it should be fixed before 9.2 release, otherwise bundler won't work on Windows.

**Comment by headius** [comment]
> my only concern is that sun.net.dns.ResolverConfiguration will become deprecated

A valid concern. There are builds of 11, can you try to test one of them too? That would get us working into the next LTS version of OpenJDK.

> it should be fixed before 9.2 release, otherwise bundler won't work on Windows.

Yikes! 😨 cc @enebo

**Comment by ahorek** [comment]
I've never used jnr.ffi before and I'm a little bit stucked :). Maybe someone could help me with it? https://github.com/jruby/jruby/pull/5178

**Comment by ahorek** [comment]
https://github.com/jruby/jruby/commit/daeb255a3398b416eac43bf9dc3b0c445f4f0781 fixed the issue, thanks @enebo

**Comment by enebo** [comment]
@ahorek thanks for the first stab too.  I agree that jnr/ffi and friends are super confusing in this case.  Using the previous call for number of bytes to next call is weird.  In Ruby FFI it was a bit easier to figure out.  Plus Ruby...

**Pull request closed without merging**
