### PR TITLE
Add Array#union

### PR DESCRIPTION
**Pull request by nomadium**
Hi folks, do we have a branch to start to merge changes related to Ruby 2.6 features?

I was reviewing some new features and decided to take a shot with implementing new Array#union method.

The implementation is more or less based on what they did in MRI [1] and is passing all its related tests [2].

For more information, please see feature #14097 [3].

Thanks in advance for any feedback.

1. https://github.com/ruby/ruby/commit/744e816f55757df92caa49b4787cf06af6120a20
2. https://github.com/ruby/ruby/blob/v2_6_0_preview3/test/ruby/test_array.rb#L1931-L1967
3. https://bugs.ruby-lang.org/issues/14097

### CODE REVIEW

**Comment by lopex** [comment]
This has changed quite a bit in mri trunk, also, should this be small array aware ?

**Comment by nomadium** [comment]
That's right, they have refactored it. It'll take that into consideration to update this PR.

**Comment by nomadium** [comment]
I took into consideration the last changes in MRI for that method and now is also small array aware. I just pushed a new commit.

**Comment by enebo** [comment]
Can you make a benchmark to see what gain we get from having small array path

**Comment by nomadium** [comment]
Sure, I’ll post the benchmark results later today.
-- 
Miguel Landaeta, nomadium at gmail.com
secure email with PGP 0x6E608B637D8967E9 available at http://miguel.cc/key
"Faith means not wanting to know what is true." -- Nietzsche

**Comment by nomadium** [comment]
@enebo I believe we get clear performance improvements by having the small array code path:

This is the code for the benchmark (I just copied part of the code from MRI tests):

```ruby
require "benchmark/ips"

Benchmark.ips do |x|
  x.report('small arrays') do
    Array[].union(Array[])
    Array[1].union(Array[])
    Array[].union(Array[1])
    Array[].union(Array[], Array[1])
    Array[1].union(Array[1])
    Array[1].union(Array[1], Array[1], Array[1])

    Array[1].union(Array[2])
    Array[1, 1].union(Array[2, 2])
    Array[1, 2].union(Array[1, 2])
    Array[1, 1].union(Array[1, 1], Array[1, 2], Array[2, 1], Array[2, 2, 2])
  end
  x.compare!
end
```

With the small arrays code path, these are the results:

```
Warming up --------------------------------------
        small arrays    24.311k i/100ms
Calculating -------------------------------------
        small arrays    505.610k (? 2.3%) i/s -      2.528M in   5.003742s
```

Without the small arrays code path, these are the results:

```
Warming up --------------------------------------
        small arrays    17.662k i/100ms
Calculating -------------------------------------
        small arrays    375.312k (? 2.1%) i/s -      1.890M in   5.037835s
```

**Comment by enebo** [comment]
@nomadium thanks!

**Comment by enebo** [comment]
@nomadium whoops I should have read this closer...this is a 2.6 feature.  I will revert this.  I can create a ruby-2.6 branch and ask you to resubmit.

**Comment by nomadium** [comment]
@enebo Thanks! I was about to ask you if it is OK to send these PRs adding Ruby 2.6 methods against master (and to be included in 9.2.5.0)? 😅

**Comment by enebo** [comment]
@nomadium resubmit these to ruby-2.6 branch I just pushed.  I should have read that description a bit closer :P

**Pull request merged**
