### PR TITLE
Fix typo in error message

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by jkutner** [comment]
This could be a problem for warbler's `runnable` feature, which uses `file:` path for jruby home :/

**Comment by mkristian** [comment]
@jkutner did you see the error message on warbler ? if so there is no problem to remove this message IMO

**Comment by jkutner** [comment]
@mkristian it seemed to "work" with the `file:/path/to/jar/...` prefix. But I was able to remove the warning by replace it with `uri:classloader:!/META-INF/...`

I say "work" because I'm stuck against another problem where `Gem::Specification` is returning `uri:classloader:...` for the executable script, but `RubyInstanceConfig.getScriptSource()` doesn't handle it.

**Comment by mkristian** [comment]
I am happy to see that "uri:classloader:" works everywhere. but I am not sure where and how this ```RubyInstanceConfig.getScriptSource()```. could give me a bit more input. maybe we should continue this on new issue or so

**Comment by jkutner** [comment]
here: https://github.com/jruby/jruby/pull/2876

**Pull request merged**
