### PR TITLE
JRuby 1.7: update jruby openssl to 0.9.18

### PR DESCRIPTION
**Pull request by cprice404**
This should address #4306 .

### CODE REVIEW

**Comment by kares** [comment]
hey, thanks! unfortunately a (1.7 specific?) regression seems to have showed up on travis-ci : 
```
     [java]   1) Error:
     [java] test_verify(OpenSSL::TestX509Store):
     [java] Java::JavaLang::ClassCastException: org.bouncycastle.jce.provider.X509CertificateObject cannot be cast to org.jruby.ext.openssl.X509Cert
     [java]     org.jruby.ext.openssl.X509StoreContext.initialize(X509StoreContext.java:132)
     [java]     org.jruby.ext.openssl.X509StoreContext.newStoreContext(X509StoreContext.java:102)
     [java]     org.jruby.ext.openssl.X509Store.verify(X509Store.java:225)
```
... so this is a blocker - will likely need to be looked at jruby-openssl.
would have halted the jossl 0.9.18 release but I assumed if the suite passes on master than its fine :(

**Comment by cprice404** [comment]
Drat.  So you think the fix for the failure will be in jruby-openssl, as opposed to in JRuby itself?  I've never worked on that codebase before, is it something you think would be approachable?  Or do you expect to have time to look into it prior to the next 1.7.x release?

**Comment by kares** [comment]
yes likely in jossl. the difference between 9K and 1.7 needs to be understood. it shouldn't be hard to figure.
never worked on the code base either before I ended up somehow maintaining it for the sole benefit of all :)

**Comment by cprice404** [comment]
Hmmm.  Well, I cloned jruby-openssl and ran it's tests against JRuby 1.7.26 based on the README, and don't get any failures.  I guess I'll see if I can repro the failure of the jruby core travis test locally.

**Comment by cprice404** [comment]
I've been intermittently trying to make some progress on this.  No major discoveries yet but it took me a while to figure out a minimal set of steps to try to repro the test failure for debugging, so I thought I'd capture that here... one of the errors can be reproduced with this command:

```
./bin/jruby -I"lib" -X-C -J-ea --1.9 -I test/externals/ruby1.9 -I test/externals/ruby1.9/ruby -r ./test/ruby19_env.rb -r minitest/excludes -I"./lib/ruby/shared" "./lib/ruby/shared/rake/rake_test_loader.rb" "test/externals/ruby1.9/openssl/test_x509store.rb"
```

**Comment by cprice404** [comment]
I left some comments about this on the original issue (#4306), as well as on a new issue I filed under jruby-openssl (jruby/jruby-openssl#113) - but the tl;dr is that I believe these same failures occur with JRuby9k, and that they slipped through the cracks because the CI for JRuby 1.7 runs the affected tests, while the CI for jruby-openssl and JRuby9k do not.

**Pull request closed without merging**
