### PR TITLE
Fix GzipWriter output

### LINKED ISSUE #1371: gzip issue with jruby and Rack::ETag
A few months ago I reported this issue against rack:

https://github.com/rack/rack/issues/571 (gzip issue with jruby and Rack::ETag)

It seems the problem may be with the way jruby is implementing gzip compression, which apparently is is doing some strange reuse of objects internally.

The bug report above includes a test case to reproduce and some analysis by @srawlins

In short the problem appears to be that rack's etag handler is concatenating parts that are rightfully assumed to be immutable but that are actually being modified in jruby's gzip implementation. Since this seems to be a jruby bug, the issue was closed a few days on the rack side.

### PR DESCRIPTION
**Pull request by dmarcotte**
GZIPOutputStream was passing one of its internal byte buffers to IOOutputStream#write, which in turn used those bytes to back the ByteList for its output.  So every subsequent time GZIPOutputStream wrote to that buffer, it overwrote the bytes behind the back of all the previous chunks of output.

Ensure that IOOutputStream is working on a copy of the bytes it gets from GZIPOutputStream to fix this issue.

Fixes #1371

Let me know if there's any questions, and thanks again!

### CODE REVIEW

**Comment by dmarcotte** [comment]
Just pushed a small extra change on this pull: b2dc3da.  Apologies for the noise.

**Comment by dmarcotte** [comment]
Just saw Travis is showing red on this pull because the 1_7 branch went red while I was working on this.  See here for a green run of these changes: https://travis-ci.org/dmarcotte/jruby/builds/87085859

**Comment by kares** [comment]
:point_up: very najs find - much appreciated!

**Comment by dmarcotte** [comment]
Thanks @kares!

**Pull request merged**
