### PR TITLE
Update to Psych 3.0.3.pre2. See ruby/psych#352.

### PR DESCRIPTION
**Pull request by headius**
Testing new Psych release. Roll forward to 3.0.3 final before merging.

### CODE REVIEW

**Comment by headius** [comment]
Ping ruby/psych#352 and @hsbt.

**Comment by headius** [comment]
I pushed a fix to psych for ruby/psych#352 and requested new preview release; when that has been tested here we can move forward with a final.

**Comment by hsbt** [comment]
@headius I just pushed https://rubygems.org/gems/psych/versions/3.0.3.pre3-java . Can you try it again?

**Comment by headius** [comment]
@hsbt Testing now!

**Comment by headius** [comment]
@hsbt Are you sure it rebuilt? I'm still getting the same error that should have been fixed by my patch on master. I confirmed it loads properly if I build and install it locally.

**Comment by hsbt** [comment]
@headius Sorry, I re-used the previous build asset. I upload pre4 binary again. Can you confirm it?

https://rubygems.org/gems/psych/versions/3.0.3.pre4-java

**Comment by headius** [comment]
@hsbt It's looking good so far! I have pushed to this PR to let CI run.

**Comment by headius** [comment]
@hsbt I found another bug with how I mapped flow styles from Psych to SnakeYAML that I fixed in ruby/psych@27232b3056d7f2a40da9f7cbf29a02579633f7e9. I pushed 3.0.3.pre5-java and it is now testing in CI.

**Comment by headius** [comment]
@hsbt I believe we can move forward with a full release of 3.0.3 now, as long as it contains all my commits to master. Thanks for your help and patience!

**Comment by hsbt** [comment]
@headius I released 3.0.3!

**Comment by headius** [comment]
@hsbt Thank you again for your help!

**Pull request merged**
