### PR TITLE
encoding parameter for Dir.open, Dir.new #3205 #4495

### LINKED ISSUE #4495: Dir.open missing optional second keyword argument
test_dir.rb:test_unknown_keywords shows one failure but no point adding the test for bogus keywords until we have any keyword argument support for it at all.

### PR DESCRIPTION
**Pull request by MariuszCwikla**
Fixes #4495 and partial fix for #3205

### CODE REVIEW

**Comment by MariuszCwikla** [comment]
In f5b78ad I've added fix for `foreach` and more tests

**Comment by kares** [comment]
looking good, still could we maybe have : `Dir.mkdir("./testDir_1")` in a test setup
and also do a test teardown part to cleanup all of the created dir's content and remove it.

**Comment by MariuszCwikla** [comment]
@kares thanks for hints. Normally I would do like you suggested, but `teardown` already performs cleanup this in it's own "interesting" ;) way:
- `setup` deletes `testDir_1` up to` testDir_5`
- `teardown` calls `setup` ;) 

Do you agree to do more refactoring (including setup/teardown and other existing tests not related to my change?)

**Comment by kares** [comment]
@MariuszCwikla oh I did not check, in that case all :+1: from me

**Comment by headius** [comment]
The modified `open` and `initialize` could be split into one- and two-argument versions, which will usually avoid the `args[]` boxing, but it's a minor item. I'll make the fix quickly on master since we'd like this in 9.2.9.

**Comment by headius** [comment]
I notice that one particular piece of logic seems to be lost: in `foreach`, if an `Encoding` was passed in instead of an options hash, it would be used without trying to dig it out of options.

Was that behavior in error? It appears to have been there since 1.9.

I will commit a change to remove the [] bits, but we do need confirmation about that logic.

**Pull request merged**
