### PR TITLE
merging jruby-1_7

### PR DESCRIPTION
**Pull request by kares**
@mkristian as I mentioned briefly ... I did attempt to merge jruby-1_7 (most changes/conflicts on my commits) but ended up being not sure about some of your (resource related) changes as the APIs are different or behaving different under master.

thus before pushing things to master I think we should get those regressions or 'new' failures out of the way ... or maybe not I [pended some failures](https://github.com/jruby/jruby/commit/2d3914ae663bbe37a81cf01922e397ad70287a23) as you noticed already.

what I think matters most is to get [travis-ci](https://travis-ci.org/jruby/jruby/builds/65570078) green (jruby-1_7 with the merging changes was all green) ... I think I'm done with my part (as far as I can tell), but let me know if you think otherwise. I'm lost in these integration-like tests anyway (do not see anything that should be related to my changes).

all is at **test-merge-1_7** branch ... feel free to commit there when you get a chance to look at these. thx

### CODE REVIEW

**Comment by mkristian** [comment]
wanted to merge my commits any ways today. will do it soon.

**Comment by mkristian** [comment]
@kares I fixed those pending tests e091e9d and ea9411c

there is still some regression with running regular tests with embedded jruby. getting there . . .

**Comment by kares** [comment]
@mkristian :trophy: I'm following your work, thanks for the `getEnvironment` "fix" as well
... let me know if there's anything on my plate - caused by my merged commits from jruby-1_7

**Comment by kares** [comment]
can we get this on master than (now that rc is out) ?

**Comment by mkristian** [comment]
@kares I would have merged it but was offline just after the rc1 release.

**Comment by kares** [comment]
@mkristian yeah NP - merged as master seemed green, thanks for all the fixes ...

**Pull request merged**
