### PR TITLE
bind (abstract) methods when implementing interface

### PR DESCRIPTION
**Pull request by kares**
there are two ways Ruby interface implementations are being generated : 
* explicitly using `Iface.impl { |name, *args| }`
* or implicitly when a block is provided for a (commonly functional) inteface last argument (proc-to-iface)

both of these add `method_missing` to the Ruby class which leads to issues when there's a naming clash in the hierarchy (e.g. `Kernel#test` with `java.util.function.Predicate#test`). these are resolved by binding implemented interface methods on the implementing Ruby class - always executing the desired user provided bits (except where he would `ImplClass.class_eval { def test ... }` the method of course).

on the Java (codegen) side, under Java 8, this further revealed [that static methods were unnecessarily being generated](https://github.com/jruby/jruby/commit/9a1e3526e89005e7c367c9c39727385b857134bb) and that interface's default methods are always being overridden ...

1. for `Iface.impl` the behaviour of implementing all methods (including defaults) was kept.
`impl(:foo, :bar)` already allows for implementing method names to be specified and an additional `impl(false)` to generate just the minimum abstract method(s) required is introduced. new code also warns on `impl(:foo)` when `"foo"` is not actually an interface method.

2. for proc-to-iface conversion overriding everything (including default) makes no sense esp. since its mostly used with functional interfaces. so this was changed and allows for slightly advanced concepts with Java 8 (e.g. `java.util.function.Function#compose`) to work correctly.

all-in-all these changes should be welcoming by JI users - it might break compatibility in very corner cases but its usually for the best to review those.

resolves https://github.com/jruby/jruby/issues/3475

### CODE REVIEW

**Comment by enebo** [comment]
@kares can you think of any breakage this will cause?  Your last sentence implies there might be breakage but do you actually know of any?

**Comment by kares** [comment]
@enebo only thing I can think of if users realize that these use `method_missing` and they would re-def it but it does make very little sense to do so. we can manage if there's complains but I doubt there will be.

**Comment by enebo** [comment]
@kares if someone might realize we used method_missing as our implementation and then monkeypatch it to change behavior I am ok with that risk.

@headius what do you think?  Can you think of any risks here?

**Comment by headius** [comment]
Ok, this one seems fine to me and I think the impl is right.

**Pull request merged**
