### PR TITLE
expand_path should use the original encoding

### LINKED ISSUE #3849: File.expand_path doesn't respect args encoding
### Environment

jruby -v
jruby 9.1.0.0 (2.3.0) 2016-05-02 a633c63 Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [mswin32-x86_64]
also doesn't work with jruby 9.0.5.0

java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### Expected Behavior

Path should be encoded in UTF8

### Actual Behavior

```
C:\jruby-9.1.0.0\bin\devel>..\jruby -S -J-Dfile.encoding=UTF-8 bundle install
UTF-8 .bundle
UTF-8 .bundle
IBM852 C:/jruby-9.1.0.0/bin/devel
IBM852 C:/jruby-9.1.0.0/bin/devel
UTF-8 config
UTF-8 config
UTF-8 C:/jruby-9.1.0.0/bin/devel/.bundle
UTF-8 C:/jruby-9.1.0.0/bin/devel/.bundle
UTF-8 .bundle
UTF-8 .bundle
IBM852 C:/Users/Pavel RosickÔöť┼╗
UTF-8 .bundle
UTF-8 .bundle
IBM852 C:/jruby-9.1.0.0/bin/devel
IBM852 C:/jruby-9.1.0.0/bin/devel
UTF-8 config
UTF-8 config
UTF-8 C:/jruby-9.1.0.0/bin/devel/.bundle
UTF-8 C:/jruby-9.1.0.0/bin/devel/.bundle
UTF-8 .bundle
UTF-8 .bundle
<b>IBM852 C:/Users/Pavel RosickÔöť┼╗</b>
TypeError: no implicit conversion from nil to integer
                        [] at org/jruby/RubyString.java:2959
             chop_basename at C:/jruby-9.1.0.0/lib/ruby/stdlib/pathname.rb:45
                      plus at C:/jruby-9.1.0.0/lib/ruby/stdlib/pathname.rb:371
                         + at C:/jruby-9.1.0.0/lib/ruby/stdlib/pathname.rb:351
                      join at C:/jruby-9.1.0.0/lib/ruby/stdlib/pathname.rb:417
          user_bundle_path at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler.rb:142
        global_config_file at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler/settings.rb:216
                initialize at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler/settings.rb:13
                  settings at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler.rb:198
                    report at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler/env.rb:28
  request_issue_report_for at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler/friendly_errors.rb:74
                 log_error at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler/friendly_errors.rb:40
      with_friendly_errors at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/lib/bundler/friendly_errors.rb:100
                     <top> at C:/jruby-9.1.0.0/lib/ruby/gems/shared/gems/bundler-1.12.1/exe/bundle:19
                      load at org/jruby/RubyKernel.java:962
                     <top> at C:/jruby-9.1.0.0/bin/bundle:22
```

### PR DESCRIPTION
**Pull request by ahorek**
fixes #3849

### CODE REVIEW

**Comment by headius** [comment]
It appears one of the tests in the JRuby suite failed, but I need to confirm if it's an appropriate test.

**Comment by headius** [comment]
Oh, silly me...it's the test you added. Testing on MRI now.

**Comment by ahorek** [comment]
@headius should be fixed now

**Comment by headius** [comment]
@ahorek Ok that matches a patch I put together here that I think fits a little better. I'll merge your PR to get the test but I'll go with my patch and you can let me know if it fixes your local issues too.

**Comment by headius** [comment]
Looks like with either of our patches I get a couple failures in MRI's suite:

```
TestFileExhaustive#test_expand_path_encoding_filesystem [/Users/headius/projects/jruby/test/mri/ruby/test_file_exhaustive.rb:660]:
<#<Encoding:UTF-8>> expected but was
<#<Encoding:US-ASCII>>.
```

Here's the code for that test:

```ruby
  def test_expand_path_encoding_filesystem
    home = ENV["HOME"]
    ENV["HOME"] = "#{DRIVE}/UserHome"

    path = "~".encode("US-ASCII")
    dir = "C:/".encode("IBM437")
    fs = Encoding.find("filesystem")

    assert_equal fs, File.expand_path(path).encoding
    assert_equal fs, File.expand_path(path, dir).encoding
  ensure
    ENV["HOME"] = home
  end
```

And here's the patch I made (applies over your PR):

```diff
diff --git a/core/src/main/java/org/jruby/RubyFile.java b/core/src/main/java/org/jruby/RubyFile.java
index 23689f1..237fd90 100644
--- a/core/src/main/java/org/jruby/RubyFile.java
+++ b/core/src/main/java/org/jruby/RubyFile.java
@@ -785,13 +785,9 @@ public class RubyFile extends RubyIO implements EncodingCapable {
 
     @JRubyMethod(name = "expand_path", required = 1, optional = 1, meta = true)
     public static IRubyObject expand_path19(ThreadContext context, IRubyObject recv, IRubyObject[] args) {
-        RubyString path = (RubyString) expandPathInternal(context, recv, args, true, false);
-        path.force_encoding(context, context.runtime.getEncodingService().convertEncodingToRubyEncoding(get_path(context, args[0]).getEncoding()));
-
-        return path;
+        return expandPathInternal(context, recv, args, true, false);
     }
 
-
     /**
      * ---------------------------------------------------- File::absolute_path
      *      File.absolute_path(file_name [, dir_string] ) -> abs_file_name
@@ -1560,6 +1556,7 @@ public class RubyFile extends RubyIO implements EncodingCapable {
 
         RubyString origPath = StringSupport.checkEmbeddedNulls(runtime, get_path(context, args[0]));
         String relativePath = origPath.getUnicodeValue();
+        Encoding enc = origPath.getEncoding();
 
         // Special /dev/null of windows
         if (Platform.IS_WINDOWS && ("NUL:".equalsIgnoreCase(relativePath) || "NUL".equalsIgnoreCase(relativePath))) {
@@ -1613,7 +1610,7 @@ public class RubyFile extends RubyIO implements EncodingCapable {
                 // this is basically for classpath:/ and uri:classloader:/
                 relativePath = relativePath.substring(2).replace('\\', '/');
             }
-            return concatStrings(runtime, preFix, extra, relativePath);
+            return concatStrings(runtime, preFix, extra, relativePath, enc);
         }
 
         String[] uriParts = splitURI(relativePath);
@@ -1627,7 +1624,7 @@ public class RubyFile extends RubyIO implements EncodingCapable {
         if (uriParts != null) {
             //If the path was an absolute classpath path, return it as-is.
             if (uriParts[0].equals("classpath:")) {
-                return concatStrings(runtime, preFix, relativePath, postFix);
+                return concatStrings(runtime, preFix, relativePath, postFix, enc);
             }
             relativePath = uriParts[1];
         }
@@ -1745,13 +1742,14 @@ public class RubyFile extends RubyIO implements EncodingCapable {
                 }
             }
         }
-        return concatStrings(runtime, preFix, realPath, postFix);
+        return concatStrings(runtime, preFix, realPath, postFix, enc);
     }
 
-    private static RubyString concatStrings(final Ruby runtime, String s1, String s2, String s3) {
+    private static RubyString concatStrings(final Ruby runtime, String s1, String s2, String s3, Encoding enc) {
         return RubyString.newString(runtime,
                 new StringBuilder(s1.length() + s2.length() + s3.length()).
-                        append(s1).append(s2).append(s3)
+                        append(s1).append(s2).append(s3).toString(),
+                enc
         );
     }
 
```

Unfortunately this is where it gets a bit tricky. Looking at MRI's C code for `expand_path` does show it trying to negotiate the incoming string's encoding and the filesystem's encoding, but it's not clear why this test should produce the filesystem encoding rather than the input encoding.

**Comment by headius** [comment]
Oh, line 660 is the first `assert_equal`.

**Comment by headius** [comment]
Ok, I've merged this to master with my additional fixes and one newly-passing ruby/spec!

@ahorek Thanks for starting this off and providing more tests! Please confirm that #3849 is fixed for you on master.

**Comment by ahorek** [comment]
@headius Tested, thanks for getting this done!

**Pull request closed without merging**
