### PR TITLE
Update specs

### PR DESCRIPTION
**Pull request by eregon**
You guys should write more specs, I didn't have to sync any spec from JRuby this time ;)

### CODE REVIEW

**Comment by eregon** [comment]
Here are the failures. Of particular interest are the String case ones, which are from specs @nirvdrum added.

```
     [exec] 1)
     [exec] Array#pack with :buffer option offset (@) is specified keeps buffer content if it is longer than offset FAILED
     [exec] Expected "123456\x00\x00\x00ABC"
     [exec]  to equal "123ABC"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:36:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:6:in `block in (root)'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 2)
     [exec] Array#pack with :buffer option offset (@) is specified fills the gap with \0 if buffer content is shorter than offset FAILED
     [exec] Expected "123\x00\x00\x00\x00\x00\x00ABC"
     [exec]  to equal "123\x00\x00\x00ABC"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:42:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:6:in `block in (root)'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 3)
     [exec] Array#pack with :buffer option offset (@) is specified does not keep buffer content if it is longer than offset + result FAILED
     [exec] Expected "1234567890\x00\x00\x00ABC"
     [exec]  to equal "123ABC"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:48:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:6:in `block in (root)'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/array/pack/buffer_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 4)
     [exec] Enumerable#all? with block yields multiple arguments when each yields multiple FAILED
     [exec] Expected [[[1, 2]], [[3, 4, 5]], [[6, 7, 8, 9]]]
     [exec] to equal [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:133:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 5)
     [exec] Enumerable#all? when given a pattern argument ignores block ERROR
     [exec] <No message>
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:147:in `block in (root)'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:147:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 6)
     [exec] Enumerable#all? when given a pattern argument returns false if the pattern ever returns false or nil FAILED
     [exec] Expected true
     [exec]  to equal false
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:178:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/all_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 7)
     [exec] Enumerable#any? with block yields multiple arguments when each yields multiple FAILED
     [exec] Expected [[[1, 2]], [[3, 4, 5]], [[6, 7, 8, 9]]]
     [exec] to equal [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/any_spec.rb:146:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/any_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 8)
     [exec] Enumerable#none? with a block yields multiple arguments when each yields multiple FAILED
     [exec] Expected [[[1, 2]], [[3, 4, 5]], [[6, 7, 8, 9]]]
     [exec] to equal [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/none_spec.rb:102:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/none_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 9)
     [exec] Enumerable#one? with a block yields multiple arguments when each yields multiple FAILED
     [exec] Expected [[[1, 2]], [[3, 4, 5]], [[6, 7, 8, 9]]]
     [exec] to equal [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/one_spec.rb:92:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/enumerable/one_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 10)
     [exec] Kernel#autoload when called from included module's method setups the autoload on the included module FAILED
     [exec] Expected nil
     [exec] to equal "/home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module.rb"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:71:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:16:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 11)
     [exec] Kernel#autoload when called from included module's method the autoload relative to the included module works ERROR
     [exec] NameError: uninitialized constant KernelSpecs::AutoloadMethod::AutoloadFromIncludedModule
     [exec] Did you mean?  KernelSpecs::AutoloadMethodIncluder
     [exec] org/jruby/RubyModule.java:3532:in `const_missing'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:79:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:16:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 12)
     [exec] Kernel.autoload when called from included module's method setups the autoload on the included module FAILED
     [exec] Expected nil
     [exec] to equal "/home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module2.rb"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:137:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:100:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 13)
     [exec] Kernel.autoload when called from included module's method the autoload is reacheable from the class too FAILED
     [exec] Expected nil
     [exec] to equal "/home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/autoload_from_included_module2.rb"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:141:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:100:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 14)
     [exec] Kernel.autoload when called from included module's method the autoload relative to the included module works ERROR
     [exec] NameError: uninitialized constant KernelSpecs::AutoloadMethod2::AutoloadFromIncludedModule2
     [exec] Did you mean?  KernelSpecs::AutoloadMethodIncluder2
     [exec] org/jruby/RubyModule.java:3532:in `const_missing'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:145:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/autoload_spec.rb:100:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 15)
     [exec] Kernel#warn :uplevel keyword argument does not prepend caller information if line number is too big FAILED
     [exec] Expected:
     [exec]   $stderr: "warning: foo\n"
     [exec]      got:
     [exec]   $stderr: "org/jruby/RubyKernel.java:1272: warning: foo\n"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:98:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 16)
     [exec] Kernel#warn :uplevel keyword argument prepends even if a message is empty or nil ERROR
     [exec] TypeError: no implicit conversion of nil into String
     [exec] org/jruby/RubyString.java:1152:in `+'
     [exec] org/jruby/RubyKernel.java:1282:in `warn'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/classes.rb:416:in `f1'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/classes.rb:412:in `f2'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/classes.rb:408:in `f3'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/fixtures/classes.rb:404:in `f4'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:106:in `block in (root)'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:106:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 17)
     [exec] Kernel#warn :uplevel keyword argument raises ArgumentError if passed negative value ERROR
     [exec] Java::JavaLang::ArrayIndexOutOfBoundsException: -1
     [exec] org.jruby.RubyKernel.warn(RubyKernel.java:1279)
     [exec] org.jruby.RubyKernel$INVOKER$s$warn_DBG.call(RubyKernel$INVOKER$s$warn_DBG.gen)
     [exec] org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:801)
     [exec] org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
     [exec] org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:365)
     [exec] org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:201)
     [exec] org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
     [exec] org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
     [exec] org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:129)
     [exec] org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:139)
     [exec] org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:79)
     [exec] org.jruby.runtime.Block.call(Block.java:124)
     [exec] org.jruby.RubyProc.call(RubyProc.java:286)
     [exec] org.jruby.RubyProc.call(RubyProc.java:266)
...
     [exec] 
     [exec] 18)
     [exec] Kernel#warn :uplevel keyword argument raises ArgumentError if passed -1 FAILED
     [exec] Expected ArgumentError but no exception was raised (nil was returned)
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:123:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/kernel/warn_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 19)
     [exec] Marshal.dump when passed a StringIO should raise an error FAILED
     [exec] Expected TypeError
     [exec] but no exception was raised ("\x04\bo:\rStringIO\x00" was returned)
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/marshal/dump_spec.rb:547:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/marshal/dump_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 20)
     [exec] String#capitalize full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/capitalize_spec.rb:44:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/capitalize_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 21)
     [exec] String#capitalize! full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/capitalize_spec.rb:125:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/capitalize_spec.rb:97:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 22)
     [exec] String#downcase full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/downcase_spec.rb:37:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/downcase_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 23)
     [exec] String#downcase! full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/downcase_spec.rb:120:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/downcase_spec.rb:98:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 24)
     [exec] String#swapcase full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/swapcase_spec.rb:37:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/swapcase_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 25)
     [exec] String#swapcase! full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/swapcase_spec.rb:112:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/swapcase_spec.rb:90:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 26)
     [exec] String#undump Limitations cannot undump non ASCII-compatible string ERROR
     [exec] RuntimeError: non-ASCII character detected
     [exec] org/jruby/RubyString.java:2079:in `undump'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/undump_spec.rb:408:in `block in (root)'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/undump_spec.rb:408:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/undump_spec.rb:6:in `block in (root)'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/undump_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 27)
     [exec] String#upcase full Unicode case mapping updates string metadata FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/upcase_spec.rb:37:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/upcase_spec.rb:5:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 28)
     [exec] String#upcase! full Unicode case mapping updates string metadata for self FAILED
     [exec] Expected false to be true
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/upcase_spec.rb:117:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/string/upcase_spec.rb:95:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] 
     [exec] 29)
     [exec] Thread::Backtrace::Location#base_label when call frame is inside a block returns the name of the method that contains the block FAILED
     [exec] Expected "block in block_location"
     [exec]  to equal "block_location"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/thread/backtrace/location/base_label_spec.rb:19:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1741:in `all?'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] org/jruby/RubyArray.java:1802:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/thread/backtrace/location/base_label_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:994:in `load'
     [exec] org/jruby/RubyBasicObject.java:2609:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1802:in `each'
```

**Comment by eregon** [comment]
The CI for specs passes now, I'll merge.

**Comment by headius** [comment]
FWIW, most of the specs that come from JRuby issues are contributed by the bug reporter directly to ruby/spec.

**Comment by eregon** [comment]
> If there are no specs, it means we did not find any untested behaviors during our work since the last sync.

Awesome then :)
I just meant it as an encouraging statement to write more specs because there are definitely some not-so-well tested areas.

> FWIW, most of the specs that come from JRuby issues are contributed by the bug reporter directly to ruby/spec.

Right, thank you for encouraging them to contribute to ruby/spec!

Both are fine for me.
One advantage of having them directly in JRuby is they can be run from the moment the PR is merged, e.g. to ensure a fix does not regress and pass the spec. One advantage of having them directly in ruby/spec is they might get more initial spec review.

**Comment by headius** [comment]
> One advantage of having them directly in ruby/spec is they might get more initial spec review.

That's the main reason I usually direct them to ruby/spec...especially when they're adding specs for something that never had specs before, rather than just adding a couple cases.

**Pull request merged**
