### PR TITLE
Correct fiddle values so things like size_t work as expected

### LINKED ISSUE #7883: NoMethodError when using Fiddle struct with size_t field
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`): `jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 17.0.7+7 on 17.0.7+7 +jit [x86_64-linux]`

```
$ ruby -rfiddle/import -e 'module M; extend Fiddle::Importer; Buffer = struct ["char *value", "size_t length"]; end'
NoMethodError: undefined method `>' for nil:NilClass
    alignment at /home/eregon/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/fiddle/struct.rb:285
         each at org/jruby/RubyArray.java:1989
    alignment at /home/eregon/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/fiddle/struct.rb:279
       create at /home/eregon/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/fiddle/struct.rb:253
  module_exec at org/jruby/RubyModule.java:3728
   initialize at org/jruby/RubyModule.java:2943
   initialize at org/jruby/RubyClass.java:957
          new at org/jruby/RubyClass.java:904
       create at /home/eregon/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/fiddle/struct.rb:216
       struct at /home/eregon/.rubies/jruby-9.4.3.0/lib/ruby/stdlib/fiddle/import.rb:222
    <class:M> at -e:1
       <main> at -e:1
```

But this works fine in CRuby.
Pretty much blocks using Fiddle for YARP in https://github.com/ruby/yarp/pull/1112

### PR DESCRIPTION
**Pull request by enebo**
Hmm a lot of wrong values and some extra ones MRI does not have.  Maybe fixes #7883

### CODE REVIEW

**Comment by ahorek** [comment]
yeah, some of these values are wrong. Also, they're platform-specific like 32 vs 64bit, Windows vs Linux... etc. we should generate them like TR does https://github.com/oracle/truffleruby/blob/master/lib/truffle/truffle/fiddle_backend.rb

**Comment by ahorek** [comment]
fiddle tests are currently disabled https://github.com/jruby/jruby/blob/master/test/mri.stdlib.index#L90 IIRC there were many issues with the pointer logic...

**Comment by enebo** [comment]
@ahorek yeah generation sounds totally right.  The FFI pointer thing I noticed was strcpy in libc would return an FFI::Pointer and not the String it represents.  Amusingly I could never the get pointer to print out the actual value (although the actual argument which also was represented by the pointer did become a valid String so I just didn't figure out the magic).

**Comment by enebo** [comment]
This PR was just seeing how quickly I could get around a problem.  I think we need a broader effort to fix this (and that is not this).  Closing.

**Pull request closed without merging**
