### PR TITLE
[Truffle] Add MRI tests to Travis builds and update the jt tool.

### PR DESCRIPTION
**Pull request by bjfish**

### CODE REVIEW

**Comment by chrisseaton** [comment]
I'm going to let Travis run on this one.

**Comment by bjfish** [comment]
@chrisseaton @nirvdrum @eregon I thought it would make sense for `jt test` to run all tests and then `jt test` would become `jt test specs`.

**Comment by chrisseaton** [comment]
You've got it so that it's

```
jt test specs spec/ruby/language/while_spec.rb
```

But I think we can look at the path you supply to work out if it's MRI or RubySpec. We can tel the difference between

```
jt test spec/ruby/language/while_spec.rb
```

and

```
jt test test/test/mri/ruby/test_whileuntil.rb
```

automatically. Then `jt test` should probably run everything, `jt test specs` just specs, and `jt test specs fast` only the fast specs.

**Comment by bjfish** [comment]
@chrisseaton updated jt per your comment

**Pull request merged**
