### PR TITLE
Implement Integer.sqrt

### PR DESCRIPTION
**Pull request by nomadium**
Hi folks,

I was taking a look at open jruby issues and how to contribute with adding Ruby 2.5 support, so I prepared this small pull request.

I believe this is not a priority right now since Ruby 2.5 is not released yet, but I decided to contribute anyway, so I'm eager to receive feedback and check if I'm going in the right direction with this.

Please consider this as a WIP, since I could not see the results of the introduced tests in Travis although is working fine for me when I manually tested it in jirb.

Thanks,

### CODE REVIEW

**Comment by enebo** [comment]
@nomadium I believe the code is alright.  The tests themselves we actually get upstream from MRI.  So while I merged those tests in they will at some point get wiped out when we resync with MRI.

The solutions to this problem is either:
a) resubmit them to ruby-lang MRI project
b) rewrite them as specs for ruby/spec (which is getting a lot of contributions lately -- probably most preferred).
c) tell us you did enough hard work and we can try and push these tests upstream.

If these were gotten from upstream then I guess that is d) and we will get them next time we sync with their test suite :)

**Comment by nomadium** [comment]
@enebo Oh, good to know about the tests. Don't worry about it since I just copied them from MRI 2.5 test suite, so you are right about option d).

Thanks for reviewing and accepting the contribution so fast. :)

**Comment by enebo** [comment]
@nomadium yeah thanks for the contribution.  Keep going! :)

**Comment by nomadium** [comment]
Add link to the Ruby 2.5 support tracking issue: https://github.com/jruby/jruby/issues/4876

**Pull request merged**
