### PR TITLE
Add File#empty? and File#zero? methods

### PR DESCRIPTION
**Pull request by maclover7**
TODO:

- get tests passing
- add support for IO objects as argument to method (and add tests for this behavior)

### CODE REVIEW

**Comment by kares** [comment]
seems that its not compilable: 
*src/main/java/org/jruby/RubyFile.java:[1532,28] error: no suitable method found for newFileStat(String)*

**Comment by enebo** [comment]
@maclover7 @kares Amazingly someone else had submitted a PR before you and I landed it but perhaps a single stat is better than an exist? + stat() hmm.  exist? on java.io.File is quicker than us performing a stat via jnr-posix but I am guessing more than half the time you expect the file to exist so you are doing two things...

**Comment by enebo** [comment]
The other PR probably works better on a minutes reflection as this mechanism will raise an ENOENT or ENODIR I think if the file does not actually exist in stat.setup().

@kcdragon @maclover7 what would work and if either of you are up for it would be to do something like:

```text
file = JRubyFile.createResource(runtime, filename);
if file == null then 
  false
else 
  file.stat.exist?
end
```
We try really hard to avoid exception when we can as they are expensive.  This above approach will eliminate the original exist() + stat() calling on existing file (which is two stat() calls) to a single one.

**Comment by enebo** [comment]
Open a new PR if either of you want to take that on.   I am closing this one.

**Pull request closed without merging**
