### PR TITLE
only require 'java', users should explicitly require 'jruby'

### PR DESCRIPTION
**Pull request by kares**
seems to makes sense as using JRuby internals make the runtime "dirty"
e.g. `ObjectSpace` will end up finding invalid class pieces (e.g. for UNDEF)

still, its kind of a small "break" in term-of backwards compatibility
although most scripts floating around do the explicit require 'jruby'
... before scripting with internals such as `JRuby.runtime`

left-over from #5205 as noted at #5233

### CODE REVIEW

**Comment by kares** [comment]
marking for 9.2 ... its not a hard requirement, more of a discussion - we could post-pone for 9.23 
would be nice to have "less" loading by default
... and as noted above the internals are changing some class internals atm: see https://github.com/jruby/jruby/issues/4528

**Comment by headius** [comment]
@enebo @kares Where do we stand on this? I'm not opposed, but I have no idea whether these features are in use elsewhere.

**Comment by enebo** [comment]
I believe we should constrain require 'jruby' to only the places we know it will be used.  Putting it near the top of JI makes no sense to me.  So I think we should apply this PR but I also wonder why it is here at all?  Do we use #reference or something somewhere?  If so the second part of this PR would be to put the include wherever we do that.

**Comment by kares** [comment]
think it has been there historically to have `JRuby.runtime` available - mostly due ext loading.
but we know have a better way of loading exts using `JRuby::Util.load_ext(name)` which avoids initializing JI for JRuby's internals ... 
on places JRuby still needs `JRuby.runtime` an explicit `require 'jruby'` should do. 
the only down side this has is that it might break some extensions 
but I believe most of them should `require 'jruby'` as they use `JRuby.runtime`

**Comment by enebo** [comment]
9.3.0.0 seems like a good time...significant # and if this does break some extensions we have some time to get them to add a single line to fix it.

**Comment by kares** [comment]
okay - will update PR as this implicit `require 'jruby'` now lives in Java

**Comment by kares** [comment]
PR is now ready ... the `require 'jruby'` removal is pretty much just [two lines](https://github.com/jruby/jruby/pull/5381/files#diff-a40568b9da02963919222c8b1eb53774L1735)
needed to adjust tests and one place we assumed the library to be loaded, also avoided the requirement (to `require 'jruby'`) from `io/nonblock` (would cause self-reflection on JRuby's Java classes so its all for the best)

**Comment by headius** [comment]
I'm approving this but it does feel a little weird now to have `JRuby` defined by default without any methods in it. Perhaps it was a bad idea originally to use the namespace directly for all these methods that would be better in their own namespaces (compilation utilities etc).

in any case, I'm fine going forward with this since most people don't even know about these utilities, and they're very much JRuby-specific anyway.

**Pull request merged**
