### PR TITLE
Improve Open3 on Windows

### PR DESCRIPTION
**Pull request by headius**
The Open3 library needs some love to be more functional on Windows.

We have never gotten back to implementing `spawn` properly on Windows, which is heavily used by Open3 for all its popen forms. To get around this, Windows will fall back on an older version of popen3 that only uses JVM processes. Unfortunately, that's the only method we patch, so [others like open2e](https://github.com/jruby/jruby/issues/4943) still try to use the broken spawn logic.

It should not be difficult to patch the other popen forms, since they're mostly just subsets of popen3.

### CODE REVIEW

**Comment by headius** [comment]
We may want to incorporate someone else's library into JRuby for Windows support, like https://github.com/enkessler/childprocess or https://github.com/djberg96/win32-process. Both use FFI to do processes "the right way" on Windows, and that would save us reimplementing things.

**Comment by headius** [comment]
My mistake...childprocess just wraps ProcessBuilder as best it can, and win32-process only provides additional methods related to Windows.

**Comment by JasonLunn** [comment]
Since this was added to the list of 9.2 Projects, is this still a blocker for the release of 9.1.17.0?

**Comment by enebo** [comment]
I moved this to .18 but I am unsure if it is resolved for .17?

**Comment by headius** [comment]
This has largely been superseded by #6649 which greatly improved the functionality of open3 on Windows, combined with other fixes for subprocess launching on non-native-process environments (like Windows).

**Pull request closed without merging**
