### PR TITLE
backport BigDecimal .to_r for #3728

### PR DESCRIPTION
**Pull request by ahorek**
#3728

### CODE REVIEW

**Comment by headius** [comment]
You using 1.7 eh? Seems fine to backport this if it's needed. We'll let CI run and then merge it.

**Comment by ahorek** [comment]
I think that this change is isolated and can be safely backported (if 1.7 is still maintained). But it's not a real issue for me, I'm using 9k :)

**Comment by headius** [comment]
Not sure why two of the builds failed so I restarted them to see.

**Comment by headius** [comment]
I'm going to try to kick that test-extended job one more time. I see a "Killed" in the log which usually means a JVM process crashed somewhere.

**Pull request merged**
