### PR TITLE
Backport FFI from master

### LINKED ISSUE #6742: Backport FFI from master
For #6732 we should backport the FFI from master, which would let us align the .rb files.

### PR DESCRIPTION
**Pull request by headius**
This backports FFI from master so that we can source all Ruby
files from the gem rather than manually updating. This will fix
issue #6732 for JRuby 9.2.20.0 and higher.

Fixes #6742.

### CODE REVIEW

**Comment by headius** [comment]
A bit of a snag here is that the ffi.rb from the gem is guarded to only be loadable on JRuby 9.3 or higher, due to 9.2 having an incompatible extension.

@enebo If we want to do this backport, we will need to get @larskanis to release a version of the ffi gem that lowers that guard to 9.2.20. Currently it is not possible to test this PR because ffi.rb does not load and it is needed by many libraries at boot.

The alternative would be to just update a minimal part of the ffi ruby code to satisfy #6732.

**Comment by larskanis** [comment]
I can make a new ffi release with lowered JRuby check.

**Comment by headius** [comment]
@larskanis Would you be willing to push a prerelease gem that lowers the check to 9.2.20? I am not yet sure whether we would make this move in that release or push out another lightweight fix release (for e.g. #6745) before making this larger change to FFI.

**Comment by larskanis** [comment]
ffi-1.15.4.pre1 is pushed with the version guard lowered to 9.2.20.

**Comment by larskanis** [comment]
@headius Do you still plan to backport changes to ffi to jruby-9.2.20? Or should I revert to 9.3.0 in the next ffi release?

**Comment by headius** [comment]
@larskanis I will get back to this today or tomorrow, thank you for checking!

**Comment by headius** [comment]
We'll see how CI goes with the prerelease FFI gem.

**Comment by headius** [comment]
@larskanis This is looking pretty solid now, thank you for the help! I will merge this and update to the released 1.15.4 in some order. Just let me know when the full release is available.

**Pull request merged**
