### PR TITLE
add integer pointer memory strategy

### PR DESCRIPTION
**Pull request by danini-the-panini**
Allows implicitly passing integers into FFI functions that take pointers, using the passed in integer as the address.

This mimics the behavior of CRuby.

### CODE REVIEW

**Comment by danini-the-panini** [comment]
@headius I've added a naive integer pointer parameter strategy, but it's causing a segfault. I thought simply wrapping the integer using NativeMemoryIO would work, but apparently not. Any ideas?

On a promising note, it seems to allow some of mittsu's examples to run, although most of them do segfault.
image

**Comment by headius** [comment]
Hmm I would have expected that to work ok. Can you point me toward a segfault report or show me how to generate the same error?

**Comment by danini-the-panini** [comment]
@headius You can trigger a segfault by just running the ffi specs. I don't even know which spec is actually failing since it crashes the whole VM. Also I haven't figured out how to debug JNI yet, any tips?

In the meantime, I've managed a workaround in Fiddle's FFI backend: https://github.com/ruby/fiddle/pull/162

**Comment by headius** [comment]
@danini-the-panini Looking into this today. If you can stop by our Matrix channel I'll be in the office.

**Comment by headius** [comment]
This is the spec that crashes first in the FFI suite, as a script:

```
require 'ffi'

module LibTest
  extend FFI::Library
  ffi_lib 'spec/ffi/fixtures/libtest.dylib'
  attach_function :testFunctionAdd, [:int, :int, :pointer], :int
end

function_add = FFI::Function.new(:int, [:int, :int]) { |a, b| a + b }

p LibTest.testFunctionAdd(10, 10, function_add)
```

The backtrace at the point of crash follows:

```
Current thread (0x000000013c01e400):  JavaThread "main"             [_thread_in_native, id=10243, stack(0x000000016dd00000,0x000000016df03000) (2060K)]

Stack: [0x000000016dd00000,0x000000016df03000],  sp=0x000000016df01870,  free space=2054k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000000013c01e400
C  [jffi8791215317760450613.dylib+0xdde8]  ffi_call_int+0x4cc
C  [jffi8791215317760450613.dylib+0x9420]  invokeArrayWithObjects_+0x400
C  [jffi8791215317760450613.dylib+0x9010]  Java_com_kenai_jffi_Foreign_invokeArrayReturnInt+0x2c
j  com.kenai.jffi.Foreign.invokeArrayReturnInt(JJ[B)I+0 org.jruby.dist
j  com.kenai.jffi.Invoker.invokeInt(Lcom/kenai/jffi/CallContext;JLcom/kenai/jffi/HeapInvocationBuffer;)I+38 org.jruby.dist
j  com.kenai.jffi.Invoker.invokeInt(Lcom/kenai/jffi/Function;Lcom/kenai/jffi/HeapInvocationBuffer;)I+10 org.jruby.dist
j  org.jruby.ext.ffi.jffi.DefaultMethodFactory$Signed32Invoker.invoke(Lorg/jruby/runtime/ThreadContext;Lcom/kenai/jffi/Function;Lcom/kenai/jffi/HeapInvocationBuffer;)Lorg/jruby/runtime/builtin/IRubyObject;+6 org.jruby.dist
j  org.jruby.ext.ffi.jffi.BufferNativeInvoker.call(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/RubyModule;Ljava/lang/String;[Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;+160 org.jruby.dist
j  org.jruby.ext.ffi.jffi.NativeInvoker.call(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/RubyModule;Ljava/lang/String;[Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/Block;)Lorg/jruby/runtime/builtin/IRubyObject;+36 org.jruby.dist
j  org.jruby.ext.ffi.jffi.DefaultMethod.call(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/RubyModule;Ljava/lang/String;[Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/Block;)Lorg/jruby/runtime/builtin/IRubyObject;+13 org.jruby.dist
j  org.jruby.internal.runtime.methods.DynamicMethod.call(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/RubyModule;Ljava/lang/String;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/Block;)Lorg/jruby/runtime/builtin/IRubyObject;+27 org.jruby.dist
j  org.jruby.internal.runtime.methods.DynamicMethod.call(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/RubyModule;Ljava/lang/String;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;+15 org.jruby.dist
j  org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/RubyClass;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;+33 org.jruby.dist
j  org.jruby.runtime.callsite.CachingCallSite.call(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;+60 org.jruby.dist
j  blah.invokeOther6:testFunctionAdd(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;+13
j  blah.RUBY$script(Lorg/jruby/runtime/ThreadContext;Lorg/jruby/parser/StaticScope;Lorg/jruby/runtime/builtin/IRubyObject;[Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/Block;Lorg/jruby/RubyModule;Ljava/lang/String;)Lorg/jruby/runtime/builtin/IRubyObject;+204
```

**Comment by headius** [comment]
@danini-the-panini Can you show me what this change fixed in your codebase? I'm wondering if it's perhaps a feature that Fiddle supports but FFI is supposed to error, so this spec is right for FFI but prevents some functionality Fiddle needs.

**Comment by danini-the-panini** [comment]
@headius ok that makes sense, I had a sneaky suspicion this wasn't going to be the correct fix. I had tried something similar by just adding `Integer#to_ptr` and it broke *everything*.

Fiddle does seem to allow integers as pointers in CRuby, and that is used extensively in mittsu-opengl since OpenGL has a few methods that have VOIDP arguments that are actually just used as byte offsets e.g. [glVertexAttribPointer](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml)

Here is an example use in Mittsu: https://github.com/danini-the-panini/mittsu-opengl/blob/a69434802b183577a6f0f770ca17de9d9a48d37f/lib/mittsu/opengl/geometry_like.rb#L43

In light of FFI's spec, I'll close this and finish up the fix in Fiddle's ffi_backend

**Comment by danini-the-panini** [comment]
Interestingly, I managed yesterday to run all of Mittsu's examples using this patch instead of the ffi_backend fix, and I didn't get any segfaults. This is on Apple Silicon (M2 Pro) with callbacks 🤔

**Comment by headius** [comment]
@danini-the-panini I don't think anything is wrong with the patch other than suddenly allowing integers to be passed for pointer arguments. That may be a valid feature to add, or it may lead to confusion if someone passes an integer they don't expect to become a pointer. Perhaps open an issue with ffi/ffi and we can discuss there with other stakeholders?

**Comment by danini-the-panini** [comment]
@headius Fair enough. It appears this was a feature that was removed for "JRuby compat" https://github.com/ffi/ffi/commit/59b48a924b27c1361ac2095a7f4a6668ed20eed5

**Comment by danini-the-panini** [comment]
Closing this since https://github.com/ffi/ffi/pull/1130 was closed

**Pull request closed without merging**
