### PR TITLE
Use Java's Arrays.sort

### PR DESCRIPTION
**Pull request by sri**
Java's Arrays.sort more robust and is faster is certain cases.

See https://github.com/jruby/jruby/issues/3919 and
https://github.com/sri/jruby-sort-benchmark.

### CODE REVIEW

**Comment by enebo** [comment]
@sri could you re-add the util class and @Deprecate it at the top.  I do not know if extensions use that class or not but it is public.

**Comment by sri** [comment]
@enebo Done!

**Comment by enebo** [comment]
@sri thanks for the PR and the time taken to show Java's sort has improved!

**Comment by sri** [comment]
@enebo Great! Thanks for all the pointers!!

**Pull request merged**
