### PR TITLE
Use com.jcraft.jzlib.JZlib instead of hacking the internals of java.util.zip.CRC32

### PR DESCRIPTION
**Pull request by jmiettinen**
The code the seems to be a remnant of the time before `JZLib` and uses internals of `java.util.zip.CRC32` when same thing could be achieved through `JZLib`. 

This can cause a performance regression as methods in `CRC32` use intrinsics, but I would not _expect_  that to be major issue as running a lot of `CRC32` does not sound like the ideal use case for JRuby.

This should remove one invasive access warning from #4834

### CODE REVIEW

**Comment by jmiettinen** [comment]
Now that I got the results deciphered, it seems that there's actually a problem there in `CRC32.gf2_matrix_times`.

I'll look into this.

**Comment by headius** [comment]
@jmiettinen Any luck?

**Comment by jmiettinen** [comment]
I'll check this out on easter holidays this weekend.

**Comment by headius** [comment]
Not a super time-critical item so don't sweat it 😀 Looking at 9.2 release in about a month.

**Comment by jmiettinen** [comment]
Is there  a way to run the build again as I don't see my changes stalling the build totally?

**Comment by headius** [comment]
I restarted the whole thing. But when did you pull this from master? We haven't tagged off or completed the remaining 2.5 failures, so that could be the source of much of this. The hangs are unfortunately elusive...something concurrency-related in MRI's tests that we stumble over.

**Comment by jmiettinen** [comment]
I probably should've started from some known-to-work tag instead of just branching from whatever happened to be the master at that time (334a7f01da17071368ddb6bcb7ea6d6b0bcb2c41).

Should I rebase this on some known-to-work-tag and force-push, or what's the preferred way of working here?

**Comment by headius** [comment]
@jmiettinen Rebasing against current master is probably your best bet. Do that and repush and we'll confirm that the failures match expected.

I'm working today to try to get master properly green, also.

**Comment by jmiettinen** [comment]
I rebased this on master that had a passing Travis build.

Now I get these errors:
```
     [exec]   test_symlinked_jar:					SyntaxError: /home/travis/build/jruby/jruby/test/jruby/jarwithoutextension:1: Invalid char `\3' ('') in expression
```

Any ideas about these? I can't really see any connection between that I've done and reading jars. @headius

**Comment by headius** [comment]
That has had some failing builds due to another PR that tried to fix some aspects of symlink traversal during load. It is probably not you. What reg did you branch from? I'm fine merging this.

**Comment by jmiettinen** [comment]
I rebased this on https://github.com/jruby/jruby/commit/e7bf9d18e57f4f96da8a091b5d916a67d1230337 which has a passing build: https://travis-ci.org/jruby/jruby/builds/367136555. Also, there does not seem to be any connection between CRC32 and the JAR-tests.

That's why I am a bit confused here.

**Comment by kares** [comment]
due some local issues with Java 8 I'm now running under 9 and hit this 3 liner warning.
considering merging as all of the failures seem non related -> have seen them on master

**Comment by kares** [comment]
vefiried and landed manually as: https://github.com/jruby/jruby/commit/f1f2c7292ac8be81c4f40ed347076536fc437723

**Pull request closed without merging**
