### PR TITLE
truffle modular

### PR DESCRIPTION
**Pull request by mkristian**
this is a follow up of #2466 to propose a slightly different setup. it basically introduce a jruby-trufle artifact which can be easily exceluded using the jruby amven artifact. jruby-jars gem takes advantage of it as well, i.e. jruby-core jar there is already truffle free.

### CODE REVIEW

**Comment by headius** [comment]
+1 looks good to me. I'd say we also remove it from jruby-complete, since anyone using jruby-complete can just add jruby-truffle to deps and it will be there.

**Comment by headius** [comment]
This can merge now.

**Comment by mkristian** [comment]
yes. beside this some cleanup is needed - readline, ripper, back to
SNAPSHOT version, etc

but this can go in as is.

**Comment by headius** [comment]
I updated the patch and cleaned up some dependencies and force pushed to the PR branch.

We need to fix -X+T at command line before we merge this, so truffle remains functional at command line. We can do that either in the launcher (requires jruby-launcher work in C/++) or shade it into lib/jruby.jar.

**Comment by mkristian** [comment]
shade it the truffle into lib/jruby.jar

**Comment by mkristian** [comment]
merged manually

**Pull request closed without merging**
