### PR TITLE
[#4353] Ignore consecutive DOUBLE_STAR  in glob_helper.

### PR DESCRIPTION
**Pull request by sumitmah**

### CODE REVIEW

**Comment by kares** [comment]
najs! any chance for a cleanup or even better use Dir.tmpdir as a base so we do not have to worry about?

**Comment by sumitmah** [comment]
@kares In the tests you're asking?

**Comment by kares** [comment]
yeah just whatever to cleanup the created dirs e.g. an `ensure FileUtils.rm_r 'testDir_bug4353'`

**Comment by sumitmah** [comment]
@kares done!

**Comment by kares** [comment]
@sumitmah thank you! 
@headius @enebo this seems good to go for 9.1.7 ... need another set of eyes to confirm.

**Comment by enebo** [comment]
@kares I would prefer to wait on this one since it has been wrong since the beginning of JRuby and we can just merge right after 9.1.7.0.

**Comment by kares** [comment]
@enebo np, your call

**Pull request merged**
