### PR TITLE
Add optional argument to start and garbage_collect

### PR DESCRIPTION
**Pull request by JasonLunn**
Proposed fix for #6818

### CODE REVIEW

**Comment by ahorek** [comment]
could you also change it at https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyObjectSpace.java#L194 and remove a tag https://github.com/jruby/jruby/blob/master/spec/tags/ruby/core/gc/start_tags.txt#L1 ?

**Comment by JasonLunn** [comment]
@ahorek - thanks for the pointers - added your suggestions.
@headius - There was no spec tag to remove for the missing keyword argument support for ObjectSpace, so I assume that means there was no compliance test that was failing without it. Does one add those such a test directly in the JRuby repo, or does one need to contribute that upstream somewhere?

**Comment by ahorek** [comment]
https://github.com/ruby/spec/blob/master/core/objectspace/garbage_collect_spec.rb#L3 is the right place

**Comment by ahorek** [comment]
one more place https://github.com/jruby/jruby/blob/master/spec/jruby.mspec#L14

**Comment by headius** [comment]
You can also add new specs to our repository directly, under `spec/ruby` which is equivalent to the https://github.com/ruby/spec repository.

FWIW, as you may have noticed GC.start is a no-op on JRuby, since the JVM GC is a very different beast than the CRuby GC and we do not really have direct control over it. I don't see us changing that any time soon.

**Comment by JasonLunn** [comment]
Updated `jruby.mspec` and opened https://github.com/ruby/spec/pull/849

**Pull request merged**
