### PR TITLE
[Truffle] Fixing Symbol#<=>, Implementing Symbol Methods

### PR DESCRIPTION
**Pull request by bjfish**
Fixing Symbol#<=>, Implementing Symol#capitalize, Symbol#casecmp,  Symbol#downcase, Symbol#encoding, Symbol#intern

### CODE REVIEW

**Comment by chrisseaton** [comment]
These changes have caused a failure in our FindBugs tests - https://github.com/jruby/jruby/commit/ffdb5da5d255711b7fedc49f1c391f1d4e3c5c27#commitcomment-9947895.

Normally I wouldn't bother you with that as you weren't to know it was there, but since you seem interested in committing quality code I'll involve you in that part of our testing infrastructure. Could you take a look? They look simple.

**Comment by bjfish** [comment]
@chrisseaton I can take a look at these.  Is there a command I should run locally before check in?

**Comment by chrisseaton** [comment]
Oh yeah sorry, it's, `function jt { ruby tool/jt.rb $@; }` and then `jt findbugs`. JT is our Truffle specific build tool and has various useful things. https://github.com/jruby/jruby/blob/master/tool/jt.rb.

**Comment by nirvdrum** [comment]
And now I see I missed the previous discussion about FindBugs.  Oops.  I was looking at the code/commit comments, not the PR comments.  It looks like you're on your way now.

**Pull request merged**
