### PR TITLE
Catch LinkageError during DynamicScope generation.

### PR DESCRIPTION
**Pull request by snowp**
When multiple threads are generating the same DynamicScope class, both
threads may try to generate the same class at the same time. When the second
thread hits defineClass, it throws a LinkageError because the class has already
been defined.

With this change we catch this exception and call loadClass to get the class that
the previous thread created.

### CODE REVIEW

**Comment by headius** [comment]
Maybe we should just lock around the class generation bit?

**Comment by headius** [comment]
I will incorporate your patch but with some double-checked locking around class generation, so we can simply avoid the exception when there's parallel generation going on.

**Comment by headius** [comment]
Great find, thanks!

**Comment by snowp** [comment]
Thanks for the fast response!

**Pull request closed without merging**
